window.lectureLibrary = [
    /* =========================================================================
       SEMESTER 5 SUBJECTS
       ========================================================================= */

    // --- CS-501: Theory of Computation (TOC) ---
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'Theory of Computation Complete Playlist',
        lecturer: 'Neso Academy',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['Finite Automata', 'DFA/NFA', 'Regular Expressions', 'CFG', 'PDA', 'Turing Machines'],
        description: 'Comprehensive university sequence covering deterministic/non-deterministic finite automata, regular languages, context-free grammars, pushdown automata, and Turing machines.',
        url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRgp46KUv4ZY69yXmpwKOBlv',
        lectureKey: 'cs501-neso-toc-full'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'TOC Full Course for Semester Exams & GATE',
        lecturer: 'Gate Smashers (Varun Singla)',
        type: 'playlist',
        typeLabel: 'Exam Prep Series',
        topics: ['DFA Minimization', 'Myhill-Nerode', 'Chomsky Hierarchy', 'Pumping Lemma', 'Undecidability'],
        description: 'Fast-paced, exam-oriented explanations with shortcut tricks for DFA minimization, regular grammar identification, closure properties, and the halting problem.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiFM9Lj5G9G_76adtyb4ef7i',
        lectureKey: 'cs501-gate-smashers-toc'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'Automata Theory and Formal Languages',
        lecturer: 'Abdul Bari',
        type: 'playlist',
        typeLabel: 'Deep-Dive Playlist',
        topics: ['Automata Fundamentals', 'Transition Diagrams', 'Equivalence of DFA & NFA', 'Mealy & Moore Machines'],
        description: 'Crystal-clear graphical visualizations and derivations of state transitions, epsilon-NFA conversions, and language acceptance proofs.',
        url: 'https://www.youtube.com/playlist?list=PLDN4rrl48X7AXx34VAF2X7nPrT42qd_PQ',
        lectureKey: 'cs501-abdul-bari-automata'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'Introduction to Theory of Computation & Automata',
        lecturer: 'Neso Academy',
        type: 'video',
        typeLabel: 'Concept Primer',
        topics: ['Alphabets & Strings', 'Formal Languages', 'Grammar Basics'],
        description: 'Foundational introduction clarifying alphabets, formal language operations (concatenation, Kleene star), and automata classification.',
        url: 'https://www.youtube.com/watch?v=58N2N7zJGrQ',
        lectureKey: 'cs501-neso-toc-intro'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'DFA Minimization Algorithm with Solved Examples',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Numerical Masterclass',
        topics: ['DFA Minimization', 'Equivalence Theorem', 'Table Filling Method'],
        description: 'Step-by-step tutorial on reducing redundant states in Deterministic Finite Automata using the partition and table-filling methods.',
        url: 'https://www.youtube.com/watch?v=Qa6csfkK7_I',
        lectureKey: 'cs501-dfa-minimization'
    },

    // --- CS-502: Database Management Systems (DBMS) ---
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'DBMS Complete University Course',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['ER Modeling', 'Relational Algebra', 'SQL', 'Normalization (1NF-BCNF)', 'Transactions & ACID', 'Concurrency'],
        description: 'Complete university curriculum covering relational models, tuple relational calculus, functional dependencies, decomposition, serializability, and B+ tree indexing.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiFAN6I8C9azFiMlACC577w8',
        lectureKey: 'cs502-gate-smashers-dbms'
    },
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'Database Management Systems Full Course',
        lecturer: 'Neso Academy',
        type: 'playlist',
        typeLabel: 'Structured Course',
        topics: ['Database Architecture', 'Keys (Primary, Foreign, Candidate)', 'Integrity Constraints', 'Query Optimization'],
        description: 'Rigorous engineering walkthrough of 3-tier DBMS architecture, schema design, relational integrity constraints, and query execution engines.',
        url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRi_CUQ-FXxgzKQ1dwr_ZJWZ',
        lectureKey: 'cs502-neso-dbms'
    },
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'Normalization in DBMS (1NF, 2NF, 3NF, BCNF) Made Easy',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Numerical Masterclass',
        topics: ['Functional Dependency', '1NF', '2NF', '3NF', 'BCNF', 'Lossless Decomposition'],
        description: 'Detailed walkthrough of finding candidate keys, attribute closures, canonical covers, and decomposing tables to eliminate insertion and deletion anomalies.',
        url: 'https://www.youtube.com/watch?v=5fs1hdwd4jo',
        lectureKey: 'cs502-normalization-guide'
    },
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'ACID Properties & Transaction Processing in DBMS',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Core Theory',
        topics: ['Atomicity', 'Consistency', 'Isolation', 'Durability', 'Write-Ahead Logging'],
        description: 'Clear breakdown of Atomicity, Consistency, Isolation, and Durability with real-world banking transaction schedules and recovery strategies.',
        url: 'https://www.youtube.com/watch?v=1prN0jKqA6Y',
        lectureKey: 'cs502-acid-properties'
    },
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'Relational Algebra & SQL Complete Tutorial',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Practical Walkthrough',
        topics: ['Select', 'Project', 'Cartesian Product', 'Natural Join', 'Subqueries', 'Group By'],
        description: 'Comprehensive mapping between relational algebraic operators (sigma, pi, rho, join) and production SQL queries with complex joins and aggregations.',
        url: 'https://www.youtube.com/watch?v=LJ4_CqZ1J5U',
        lectureKey: 'cs502-relational-algebra-sql'
    },

    // --- CS-503: Data Analytics ---
    {
        semester: 5,
        subject: 'cs503',
        subjectCode: 'CS-503',
        subjectLabel: 'Data Analytics',
        title: 'Complete Data Analytics & Statistics Masterclass',
        lecturer: 'Krish Naik',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['Descriptive Stats', 'Inferential Stats', 'Probability Distributions', 'Hypothesis Testing', 'Data Wrangling'],
        description: 'Hands-on curriculum spanning probability distributions (Normal, Binomial, Poisson), Z-tests, t-tests, ANOVA, and exploratory data analysis pipelines.',
        url: 'https://www.youtube.com/playlist?list=PLZoTAELRMXVMhVyr3Ri9IQ-t5QPBtxzJO',
        lectureKey: 'cs503-krish-naik-analytics'
    },
    {
        semester: 5,
        subject: 'cs503',
        subjectCode: 'CS-503',
        subjectLabel: 'Data Analytics',
        title: 'Statistics Fundamentals for Data Science',
        lecturer: 'StatQuest with Josh Starmer',
        type: 'playlist',
        typeLabel: 'Visual Intuition',
        topics: ['p-values', 'Confidence Intervals', 'Linear Regression', 'Logistic Regression', 'PCA'],
        description: 'Delightful, intuitive visual breakdowns of p-values, hypothesis tests, maximum likelihood estimation, covariance matrices, and Principal Component Analysis.',
        url: 'https://www.youtube.com/playlist?list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9',
        lectureKey: 'cs503-statquest-stats'
    },
    {
        semester: 5,
        subject: 'cs503',
        subjectCode: 'CS-503',
        subjectLabel: 'Data Analytics',
        title: 'Data Analytics Full Course in 8 Hours',
        lecturer: 'Simplilearn',
        type: 'video',
        typeLabel: 'Comprehensive Masterclass',
        topics: ['Data Wrangling', 'Exploratory Analysis', 'Predictive Modeling', 'Tableau & PowerBI', 'Case Studies'],
        description: 'End-to-end overview of data lifecycle, cleaning dirty datasets, statistical modeling, correlation analysis, and executive dashboard visualization.',
        url: 'https://www.youtube.com/watch?v=1unO5oA8oXk',
        lectureKey: 'cs503-simplilearn-analytics'
    },
    {
        semester: 5,
        subject: 'cs503',
        subjectCode: 'CS-503',
        subjectLabel: 'Data Analytics',
        title: 'Hypothesis Testing Explained with Solved Numericals',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Exam Numericals',
        topics: ['Null Hypothesis (H0)', 'Alternative Hypothesis (H1)', 'Type I & Type II Errors', 'Z-Test vs t-Test'],
        description: 'University exam problem solving for null and alternative hypotheses, rejection regions, degrees of freedom, and critical value comparisons.',
        url: 'https://www.youtube.com/watch?v=ZzeXCJ9Z6B8',
        lectureKey: 'cs503-hypothesis-testing'
    },

    // --- CS-503-CS: Cyber Security ---
    {
        semester: 5,
        subject: 'cs503-cs',
        subjectCode: 'CS-503-CS',
        subjectLabel: 'Cyber Security',
        title: 'Cryptography & Network Security Full Course',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['Classical Ciphers', 'DES & AES', 'RSA Algorithm', 'Diffie-Hellman', 'Digital Signatures', 'Firewalls'],
        description: 'Covers symmetric and asymmetric encryption, Block cipher modes (ECB, CBC, CFB), RSA key generation, SHA-256 hash algorithms, and firewall topologies.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiHcmS4i14bI0VrMbZTUvlTa',
        lectureKey: 'cs503cs-gate-smashers-security'
    },
    {
        semester: 5,
        subject: 'cs503-cs',
        subjectCode: 'CS-503-CS',
        subjectLabel: 'Cyber Security',
        title: 'CompTIA Security+ Training Course',
        lecturer: 'Professor Messer',
        type: 'playlist',
        typeLabel: 'Industry Standard Series',
        topics: ['Threats & Vulnerabilities', 'Identity & Access Management', 'PKI & Certificates', 'Incident Response'],
        description: 'Industry-standard cyber security training covering zero trust architecture, threat vectors (phishing, MITM, DDoS), malware types, and cryptographic controls.',
        url: 'https://www.youtube.com/playlist?list=PLG49S3nxzAnl4QDVqK-hOnoqcSKEIDDuv',
        lectureKey: 'cs503cs-professor-messer'
    },
    {
        semester: 5,
        subject: 'cs503-cs',
        subjectCode: 'CS-503-CS',
        subjectLabel: 'Cyber Security',
        title: 'Public Key Cryptography & RSA Algorithm Clearly Explained',
        lecturer: 'Computerphile (Dr. Mike Pound)',
        type: 'video',
        typeLabel: 'Conceptual Deep-Dive',
        topics: ['Asymmetric Encryption', 'Prime Factorization', 'Modular Inverses', 'Euler Totient'],
        description: 'Superb mathematical explanation of why RSA works, Fermat\'s Little Theorem, prime factorization trapdoors, and practical padding vulnerabilities.',
        url: 'https://www.youtube.com/watch?v=GSIDS_lvRv4',
        lectureKey: 'cs503cs-computerphile-rsa'
    },
    {
        semester: 5,
        subject: 'cs503-cs',
        subjectCode: 'CS-503-CS',
        subjectLabel: 'Cyber Security',
        title: 'Cyber Security Full Course for Beginners',
        lecturer: 'NetworkChuck',
        type: 'video',
        typeLabel: 'Hands-on Foundations',
        topics: ['Port Scanning', 'Firewalls', 'Wireshark', 'Kali Linux', 'Social Engineering'],
        description: 'Action-oriented exploration of network security, packet capturing, ports, firewalls, and defense strategies against active attacks.',
        url: 'https://www.youtube.com/watch?v=nzj7Wg46WoA',
        lectureKey: 'cs503cs-networkchuck-course'
    },

    // --- CS-504: Web Technology ---
    {
        semester: 5,
        subject: 'cs504',
        subjectCode: 'CS-504',
        subjectLabel: 'Web Technology',
        title: 'Web Development Full Course: HTML, CSS & JavaScript',
        lecturer: 'freeCodeCamp',
        type: 'video',
        typeLabel: 'Full Foundation Course',
        topics: ['Semantic HTML5', 'CSS3 Flexbox & Grid', 'JavaScript DOM', 'Event Handling', 'Responsive Design'],
        description: 'Complete front-end foundations covering modern semantic tags, responsive layouts, CSS box model, DOM manipulation, and asynchronous browser APIs.',
        url: 'https://www.youtube.com/watch?v=mU6anWqZJcc',
        lectureKey: 'cs504-fcc-web-course'
    },
    {
        semester: 5,
        subject: 'cs504',
        subjectCode: 'CS-504',
        subjectLabel: 'Web Technology',
        title: 'Modern JavaScript Full Playlist',
        lecturer: 'Net Ninja (Shaun Pelling)',
        type: 'playlist',
        typeLabel: 'JavaScript Deep Dive',
        topics: ['ES6 Syntax', 'Promises & Async/Await', 'Fetch API', 'Object-Oriented JS', 'LocalStorage'],
        description: 'Structured programming path from basic JS syntax to ES6 classes, arrow functions, promises, async/await, and REST API communication.',
        url: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9haFPT7J25Q9GRB_ZkFrQAc',
        lectureKey: 'cs504-net-ninja-js'
    },
    {
        semester: 5,
        subject: 'cs504',
        subjectCode: 'CS-504',
        subjectLabel: 'Web Technology',
        title: 'PHP & MySQL Backend Web Architecture',
        lecturer: 'Dave Gray',
        type: 'video',
        typeLabel: 'Backend Masterclass',
        topics: ['PHP Syntax', 'Form Handling (GET/POST)', 'PDO MySQL Connection', 'Session Management', 'Security'],
        description: 'Complete server-side web engineering tutorial covering PHP syntax, request handling, PDO prepared statements against SQL injection, and session auth.',
        url: 'https://www.youtube.com/watch?v=OK_JCtrrv-c',
        lectureKey: 'cs504-dave-gray-php'
    },
    {
        semester: 5,
        subject: 'cs504',
        subjectCode: 'CS-504',
        subjectLabel: 'Web Technology',
        title: 'HTTP Protocol Crash Course & RESTful APIs',
        lecturer: 'Traversy Media',
        type: 'video',
        typeLabel: 'Concept Primer',
        topics: ['HTTP Methods', 'Status Codes', 'Headers & Cookies', 'REST Architecture', 'JSON'],
        description: 'Indispensable guide to the HTTP request-response cycle, header anatomy, status codes (2xx, 3xx, 4xx, 5xx), cookies, and REST API contracts.',
        url: 'https://www.youtube.com/watch?v=iYM2zFP3Zn0',
        lectureKey: 'cs504-traversy-http-rest'
    },

    /* =========================================================================
       SEMESTER 6 SUBJECTS
       ========================================================================= */

    // --- CS-601: Machine Learning ---
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Machine Learning Specialization Playlist',
        lecturer: 'Andrew Ng / DeepLearning.AI',
        type: 'playlist',
        typeLabel: 'World-Renowned Specialization',
        topics: ['Linear Regression', 'Cost Functions', 'Gradient Descent', 'Logistic Regression', 'Overfitting & Regularization'],
        description: 'Structured machine learning curriculum taught by AI pioneer Andrew Ng, covering mathematical foundations, cost optimization, regularization, and model validation.',
        url: 'https://www.youtube.com/playlist?list=PLkDaE6sCZn6FNC6YRfRQc_FbeQrF8BwGI',
        lectureKey: 'cs601-andrew-ng-ml'
    },
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Machine Learning Full Course for Exams',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'University Exam Series',
        topics: ['Supervised vs Unsupervised', 'SVM', 'KNN', 'K-Means', 'Ensemble Learning', 'Confusion Matrix'],
        description: 'University-tailored lectures covering classification metrics, Naive Bayes classifiers, Support Vector Machines, decision boundaries, and clustering algorithms.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiHN1xU4N8I1PZgR-G0Zk_k8',
        lectureKey: 'cs601-gate-smashers-ml'
    },
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Neural Networks & Deep Learning Series',
        lecturer: '3Blue1Brown (Grant Sanderson)',
        type: 'playlist',
        typeLabel: 'Visual Math Masterpiece',
        topics: ['Perceptrons', 'Activation Functions', 'Backpropagation Math', 'Matrix Calculus in ML'],
        description: 'Internationally acclaimed visual explanation of multilayer perceptrons, gradient descent manifolds, chain rule backpropagation, and loss surfaces.',
        url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi',
        lectureKey: 'cs601-3b1b-neural-nets'
    },
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Support Vector Machines (SVM) Clearly Explained',
        lecturer: 'StatQuest with Josh Starmer',
        type: 'video',
        typeLabel: 'Algorithmic Deep Dive',
        topics: ['Maximum Margin Hyperplane', 'Support Vectors', 'Soft Margin & Slack', 'Kernel Trick (RBF)'],
        description: 'Intuitive geometric and mathematical explanation of finding optimal separating hyperplanes, soft margin slack penalty C, and mapping dimensions with Mercer kernels.',
        url: 'https://www.youtube.com/watch?v=efR1C6CvhmE',
        lectureKey: 'cs601-statquest-svm'
    },
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Decision Trees, Bagging & Random Forests',
        lecturer: 'StatQuest with Josh Starmer',
        type: 'video',
        typeLabel: 'Algorithmic Deep Dive',
        topics: ['Gini Impurity', 'Information Gain & Entropy', 'Bootstrap Aggregation', 'Out-of-Bag Error'],
        description: 'Step-by-step walkthrough of tree splitting criteria, computing Gini impurity and information gain, tree pruning, and ensemble variance reduction.',
        url: 'https://www.youtube.com/watch?v=7VeUPuFGJHk',
        lectureKey: 'cs601-statquest-random-forests'
    },

    // --- CS-602: Computer Networks ---
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Computer Networks Complete Playlist',
        lecturer: 'Neso Academy',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['OSI Model', 'TCP/IP Model', 'Framing & CRC', 'Routing Algorithms', 'TCP/UDP', 'Congestion Control'],
        description: 'Complete university computer networks sequence covering protocol stacks, data link framing, sliding window flow control, Dijkstra routing, and socket operations.',
        url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRgMCUAG0XRw78UA8qnv6jEx',
        lectureKey: 'cs602-neso-cn-full'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Computer Networks Complete University Course',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Exam Prep Series',
        topics: ['IPv4 & IPv6', 'Subnetting & CIDR', 'Dijkstra & Distance Vector', 'Three-Way Handshake', 'DNS & DHCP'],
        description: 'Exam-focused lectures with shortcut numerical solutions for IPv4 classless subnet masks, routing loops (count-to-infinity), and TCP windowing.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGFBD2-2joCpWOLUrDLvVV_',
        lectureKey: 'cs602-gate-smashers-cn'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Subnetting & CIDR Calculation Step-by-Step',
        lecturer: 'Neso Academy',
        type: 'video',
        typeLabel: 'Numerical Masterclass',
        topics: ['IPv4 Addressing', 'CIDR Notation', 'Subnet Mask Calculation', 'Usable Host Addresses', 'Block Size'],
        description: 'Definitive guide to calculating network IDs, broadcast addresses, subnet masks, and block sizes for any given CIDR prefix.',
        url: 'https://www.youtube.com/watch?v=vcArZ_sN0zI',
        lectureKey: 'cs602-subnetting-guide'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Error Detection & CRC (Cyclic Redundancy Check)',
        lecturer: 'Neso Academy',
        type: 'video',
        typeLabel: 'Numerical Masterclass',
        topics: ['CRC Generator Polynomial', 'Binary Polynomial Division', 'Checksum Calculation', 'Parity Bit Checks'],
        description: 'Essential numerical tutorial on binary polynomial long division to compute CRC remainder checksums transmitted in network frames.',
        url: 'https://www.youtube.com/watch?v=EMrY-8m8D1E',
        lectureKey: 'cs602-error-detection'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'TCP Congestion Control: Tahoe vs Reno State Machine',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Core Architecture',
        topics: ['Slow Start', 'Congestion Avoidance', 'Fast Retransmit', 'Fast Recovery', '3 Duplicate ACKs'],
        description: 'Rigorous analysis of TCP cwnd window curves, slow start threshold (ssthresh), handling timeouts vs 3 duplicate ACKs, and Tahoe vs Reno comparisons.',
        url: 'https://www.youtube.com/watch?v=yox5iXgZ5lY',
        lectureKey: 'cs602-tcp-congestion-control'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Networking from Physical Cables to Transport Layer',
        lecturer: 'Ben Eater',
        type: 'video',
        typeLabel: 'Hardware & Systems Deep Dive',
        topics: ['Ethernet Frames', 'MAC Addresses', 'ARP Requests', 'IP Routing', 'TCP Handshake'],
        description: 'Remarkable physical breadboard and oscilloscope demonstration tracing raw electric pulses up to Ethernet frames, ARP tables, and TCP packets.',
        url: 'https://www.youtube.com/watch?v=bj-YfZ9W2lM',
        lectureKey: 'cs602-ben-eater-networking'
    },

    // --- CS-603: Compiler Design ---
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'Compiler Design Full Course Playlist',
        lecturer: 'Neso Academy',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['Phases of Compiler', 'Lexical Analysis', 'FIRST & FOLLOW Sets', 'LL(1) Parsers', 'Operator Precedence', 'LR Parsers'],
        description: 'Exhaustive university curriculum covering Lexical Analysis, Context-Free Grammars, FIRST & FOLLOW derivations, Top-Down vs Bottom-Up parsers, and code optimization.',
        url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRjT3oJxFXRgjPNzeS-LFY-q',
        lectureKey: 'cs603-neso-compiler-full'
    },
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'Compiler Design University Exam Series',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Exam Prep Series',
        topics: ['Left Recursion Elimination', 'Left Factoring', 'LR(0) & SLR(1)', 'LALR(1)', 'Three-Address Code', 'DAG'],
        description: 'Concise, high-scoring university lectures on eliminating immediate and indirect left recursion, canonical collections of LR items, and syntax directed translations.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiEKtKSIHYusizkESC42diyc',
        lectureKey: 'cs603-gate-smashers-compiler'
    },
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'LL(1) Parser Construction & Parsing Table Solved Example',
        lecturer: 'Neso Academy',
        type: 'video',
        typeLabel: 'Numerical Masterclass',
        topics: ['FIRST Calculation', 'FOLLOW Calculation', 'LL(1) Table', 'Conflict Detection (First/Follow)'],
        description: 'Complete numerical derivation of FIRST and FOLLOW sets, populating the LL(1) parsing table, and verifying grammar determinism.',
        url: 'https://www.youtube.com/watch?v=cM_rI8kEwA8',
        lectureKey: 'cs603-ll1-parser-guide'
    },
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'Syntax Directed Translation (SDT) & 3-Address Code',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Intermediate Code Generation',
        topics: ['Synthesized Attributes', 'Inherited Attributes', 'S-Attributed vs L-Attributed SDT', 'Quadruples & Triples'],
        description: 'Masterclass on semantic analysis, semantic rules in parse trees, generating intermediate 3-address representations, quadruples, and triples.',
        url: 'https://www.youtube.com/watch?v=l_tT_e_uJvY',
        lectureKey: 'cs603-sdt-three-address'
    },
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'What Is a Compiler? Architecture & 6 Phases Overview',
        lecturer: 'Neso Academy',
        type: 'video',
        typeLabel: 'Concept Primer',
        topics: ['Compiler vs Interpreter', 'Analysis & Synthesis Phases', 'Symbol Table', 'Error Handler'],
        description: 'Foundational lecture introducing the 6 phases of a compiler: Lexical, Syntax, Semantic, Intermediate Code, Code Optimizer, and Target Code Generator.',
        url: 'https://www.youtube.com/watch?v=5ZmFlxrNaN8',
        lectureKey: 'cs603-compiler-intro'
    },

    // --- CS-603-CG: Computer Graphics ---
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: 'Computer Graphics Complete University Playlist',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['Raster Scan vs Random Scan', 'Bresenham Line & Circle', '2D/3D Transforms', 'Clipping Algorithms', 'Shading Models'],
        description: 'Complete university curriculum covering CRT architecture, rasterization algorithms, homogeneous coordinates, matrix transformations, and Sutherland-Hodgman polygon clipping.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGH0D4s_jO_8KjWvPzG3t3E',
        lectureKey: 'cs603cg-gate-smashers-full'
    },
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: 'OpenGL & 3D Computer Graphics Pipeline',
        lecturer: 'The Cherno (Yan Chernikov)',
        type: 'playlist',
        typeLabel: 'Engineering Deep Dive',
        topics: ['Vertex Buffers (VBO)', 'Index Buffers (IBO)', 'Shaders (GLSL)', 'Model-View-Projection (MVP)', 'Textures'],
        description: 'Industry-standard graphics programming series covering GPU architectures, vertex/fragment shaders, affine matrix transforms, and depth testing.',
        url: 'https://www.youtube.com/playlist?list=PLlrATfBNZ98foTJPJ_Ev03o2oq3-GGOS2',
        lectureKey: 'cs603cg-the-cherno-opengl'
    },
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: 'Bresenham\'s Line Drawing Algorithm Mathematical Derivation',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Numerical Masterclass',
        topics: ['Decision Parameter pk', 'Incremental Integer Arithmetic', 'Slope Conditions |m| < 1', 'Octant Symmetry'],
        description: 'Complete mathematical derivation of Bresenham\'s decision parameter pk = 2dy - dx, demonstrating why integer-only arithmetic makes it faster than DDA.',
        url: 'https://www.youtube.com/watch?v=yaUvCprc7jI',
        lectureKey: 'cs603cg-bresenham-derivation'
    },
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: '2D & 3D Geometric Transformations with Matrix Math',
        lecturer: 'Tutorials Point',
        type: 'video',
        typeLabel: 'Numerical Masterclass',
        topics: ['Translation', 'Rotation Matrix', 'Scaling Matrix', 'Homogeneous Coordinates', 'Composite Transforms'],
        description: 'Step-by-step matrix multiplication examples for translating, scaling, and rotating points about arbitrary pivot centers using 3x3 homogeneous matrices.',
        url: 'https://www.youtube.com/watch?v=T98Vb8u1t5I',
        lectureKey: 'cs603cg-transformations-matrix'
    },
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: 'Cohen-Sutherland Line Clipping Algorithm Explained',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Core Algorithm',
        topics: ['4-Bit Region Codes (TBRL)', 'Trivial Acceptance', 'Trivial Rejection', 'Intersection Calculation'],
        description: 'Clear algorithmic breakdown of 4-bit region codes (Top, Bottom, Right, Left), bitwise logical AND testing, and calculating line-window boundary intersections.',
        url: 'https://www.youtube.com/watch?v=CqHjO8fNqFs',
        lectureKey: 'cs603cg-cohen-sutherland'
    },

    // --- CS-604: Project Management ---
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'Software Engineering & Project Management Playlist',
        lecturer: '5 Minutes Engineering',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['SDLC Models', 'Agile & Scrum', 'COCOMO Model', 'CPM & PERT', 'Risk Management', 'Software Testing'],
        description: 'University syllabus covered in crisp, high-yield videos on Waterfall, Spiral, Agile Scrum ceremonies, critical path scheduling, and risk mitigation strategies.',
        url: 'https://www.youtube.com/playlist?list=PLYwpaL_SFmcCB7zUM0YSDR-1mM4KoiyLM',
        lectureKey: 'cs604-5min-pm-playlist'
    },
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'Software Engineering Complete University Course',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Exam Prep Series',
        topics: ['SRS Documentation', 'Function Point Analysis', 'Cyclomatic Complexity', 'Coupling & Cohesion', 'Black/White Box Testing'],
        description: 'Exam-focused tutorials on software requirements specifications (SRS), McCabe cyclomatic complexity, coupling vs cohesion metrics, and verification vs validation.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiEed7SKZBnC6ypFDWYLRvB2',
        lectureKey: 'cs604-gate-smashers-se'
    },
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'Agile vs Scrum Framework in 15 Minutes',
        lecturer: 'Simplilearn',
        type: 'video',
        typeLabel: 'Concept Primer',
        topics: ['Agile Manifesto', 'Sprint Planning', 'Daily Scrum', 'Product Backlog', 'Sprint Retrospective'],
        description: 'Comprehensive overview of Agile principles, user stories, burn-down charts, sprint cadences, and the distinct roles of Scrum Master, Product Owner, and Dev Team.',
        url: 'https://www.youtube.com/watch?v=2PtUC_5eAOU',
        lectureKey: 'cs604-agile-scrum-framework'
    },
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'COCOMO Model: Effort, Development Time & Cost Calculations',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Numerical Masterclass',
        topics: ['Basic COCOMO', 'Intermediate COCOMO', 'Organic, Semidetached, Embedded Modes', 'Effort Equations'],
        description: 'Step-by-step solved university numericals using COCOMO effort equation E = a*(KLOC)^b and development time equation D = c*(E)^d.',
        url: 'https://www.youtube.com/watch?v=9I5PqU_5e_U',
        lectureKey: 'cs604-cocomo-numericals'
    },
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'Critical Path Method (CPM) & PERT Chart Step-by-Step',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Numerical Masterclass',
        topics: ['Earliest Start/Finish (ES/EF)', 'Latest Start/Finish (LS/LF)', 'Total Float & Slack', 'Critical Path Identification'],
        description: 'Complete forward-pass and backward-pass numerical walkthrough on network activity diagrams to calculate total float and pinpoint zero-slack critical paths.',
        url: 'https://www.youtube.com/watch?v=4b3Xl_0Kk44',
        lectureKey: 'cs604-cpm-pert-calculations'
    },

    /* =========================================================================
       SEMESTER 7 SUBJECTS
       ========================================================================= */

    // --- CS-701: Software Architectures ---
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: 'Software Architecture Monday Masterclass Series',
        lecturer: 'Mark Richards (DeveloperToArchitect)',
        type: 'playlist',
        typeLabel: 'Industry Masterclass Playlist',
        topics: ['Architectural Styles', 'Microservices vs Monolith', 'Event-Driven Architecture', 'Service-Based Architecture', 'Architecture Katas'],
        description: 'World-class masterclasses by renowned software architecture author Mark Richards, dissecting architectural patterns, modularity trade-offs, and design governance.',
        url: 'https://www.youtube.com/playlist?list=PL9ooFrVz33mS_89Z4A_jAadkI2i5v_U7j',
        lectureKey: 'cs701-mark-richards-arch'
    },
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: 'Design Patterns & Architectural Styles',
        lecturer: 'Derek Banas',
        type: 'playlist',
        typeLabel: 'Full Patterns Course',
        topics: ['Creational Patterns', 'Structural Patterns', 'Behavioral Patterns', 'MVC & Observer', 'Adapter & Facade'],
        description: 'Comprehensive video sequence covering all Gang of Four (GoF) design patterns with clean UML diagrams, Java implementations, and architectural refactorings.',
        url: 'https://www.youtube.com/playlist?list=PLF206E906175C7E07',
        lectureKey: 'cs701-derek-banas-patterns'
    },
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: '4+1 View Model of Software Architecture & Quality Attributes',
        lecturer: 'Edureka',
        type: 'video',
        typeLabel: 'Core Curriculum Deep Dive',
        topics: ['Logical View', 'Process View', 'Development View', 'Physical View', 'Use Case Scenarios (+1)', 'ATAM Evaluation'],
        description: 'Detailed analysis of Philippe Kruchten\'s 4+1 View Model, mapping views to stakeholders, and connecting non-functional quality attributes (latency, availability, modifiability).',
        url: 'https://www.youtube.com/watch?v=4E1Uk1KqV6U',
        lectureKey: 'cs701-four-plus-one-view'
    },
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: 'Microservices & Distributed Architecture Principles',
        lecturer: 'Martin Fowler (ThoughtWorks)',
        type: 'video',
        typeLabel: 'Thought Leader Keynote',
        topics: ['Componentization via Services', 'Organized around Business Capabilities', 'Smart Endpoints & Dumb Pipes', 'Decentralized Data Management'],
        description: 'Seminal keynote by Martin Fowler explaining microservices characteristics, Conway\'s Law, independent deployability, and bounded context domain modeling.',
        url: 'https://www.youtube.com/watch?v=wgdBVIX9ifA',
        lectureKey: 'cs701-martin-fowler-microservices'
    },
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: 'Event-Driven Architecture, CQRS & Domain Driven Design',
        lecturer: 'CodeOpinion (Derek Comartin)',
        type: 'video',
        typeLabel: 'Modern Systems Architecture',
        topics: ['Event Sourcing', 'Command Query Responsibility Segregation (CQRS)', 'Message Queues', 'Outbox Pattern'],
        description: 'Superb visual guide on decoupling systems through asynchronous events, event-sourcing append-only ledgers, and resolving eventual consistency challenges.',
        url: 'https://www.youtube.com/watch?v=1xS_z3Q5W9A',
        lectureKey: 'cs701-event-driven-cqrs'
    },

    // --- CS-702: Big Data Analytics ---
    {
        semester: 7,
        subject: 'cs702',
        subjectCode: 'CS-702',
        subjectLabel: 'Big Data Analytics',
        title: 'Big Data & Hadoop Ecosystem Full Course',
        lecturer: 'Edureka',
        type: 'video',
        typeLabel: 'Complete 10-Hour Masterclass',
        topics: ['5Vs of Big Data', 'HDFS Architecture', 'MapReduce Computation', 'YARN Resource Manager', 'Pig & Hive'],
        description: 'Comprehensive 10-hour crash course covering Hadoop cluster architecture, block distribution, NameNode metadata management, MapReduce data flow, and YARN scheduling.',
        url: 'https://www.youtube.com/watch?v=1vbXmCrkT3Y',
        lectureKey: 'cs702-edureka-hadoop-full'
    },
    {
        semester: 7,
        subject: 'cs702',
        subjectCode: 'CS-702',
        subjectLabel: 'Big Data Analytics',
        title: 'Apache Spark Full Course & PySpark Architecture',
        lecturer: 'Simplilearn',
        type: 'video',
        typeLabel: 'In-Memory Analytics Course',
        topics: ['Spark Core Architecture', 'Resilient Distributed Datasets (RDD)', 'Spark SQL & DataFrames', 'Lazy Evaluation & DAG'],
        description: 'Complete guide to Apache Spark\'s in-memory computational engine, Directed Acyclic Graph (DAG) query optimization, RDD transformations vs actions, and Spark Streaming.',
        url: 'https://www.youtube.com/watch?v=d_2yR1F9C18',
        lectureKey: 'cs702-simplilearn-spark'
    },
    {
        semester: 7,
        subject: 'cs702',
        subjectCode: 'CS-702',
        subjectLabel: 'Big Data Analytics',
        title: 'HDFS Architecture & MapReduce Execution Flow',
        lecturer: 'Edureka',
        type: 'video',
        typeLabel: 'Core Architecture',
        topics: ['NameNode & DataNodes', 'Secondary NameNode Checkpointing', '3x Rack Awareness Replication', 'Map, Shuffle & Reduce'],
        description: 'Detailed mechanical walkthrough of HDFS block allocation, rack awareness fault tolerance, and the step-by-step MapReduce computation pipeline.',
        url: 'https://www.youtube.com/watch?v=4b2k9aQ1w2M',
        lectureKey: 'cs702-hdfs-mapreduce-flow'
    },
    {
        semester: 7,
        subject: 'cs702',
        subjectCode: 'CS-702',
        subjectLabel: 'Big Data Analytics',
        title: 'Big Data Analytics & NoSQL Database Architectures',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'University Exam Series',
        topics: ['CAP Theorem', 'NoSQL Classification (Key-Value, Columnar, Document, Graph)', 'HBase', 'Cassandra', 'Data Locality'],
        description: 'Clear university exam explanations of Eric Brewer\'s CAP Theorem, PACELC trade-offs, columnar storage (HBase/Cassandra), and horizontal scalability.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGNvT_uWjC5z8vM0kP6W9t8',
        lectureKey: 'cs702-gate-smashers-bigdata'
    },
    {
        semester: 7,
        subject: 'cs702',
        subjectCode: 'CS-702',
        subjectLabel: 'Big Data Analytics',
        title: 'Hadoop, HDFS & Distributed Processing Architecture',
        lecturer: 'freeCodeCamp',
        type: 'video',
        typeLabel: 'Systems Deep Dive',
        topics: ['Cluster Node Topologies', 'Fault Tolerance Mechanisms', 'Heartbeats & Block Reports', 'Data Ingestion'],
        description: 'Deep architectural walkthrough of setting up distributed data nodes, handling data corruption, automatic re-replication, and cluster balancing.',
        url: 'https://www.youtube.com/watch?v=3c_W_U2q3rA',
        lectureKey: 'cs702-fcc-hadoop-arch'
    },

    // --- CS-702-WMC: Wireless & Mobile Computing ---
    {
        semester: 7,
        subject: 'cs702-wmc',
        subjectCode: 'CS-702-WMC',
        subjectLabel: 'Wireless & Mobile Computing',
        title: 'Mobile Computing & Cellular Communication Playlist',
        lecturer: 'Neso Academy',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['Cellular Concept', 'Frequency Reuse', 'Channel Assignment', 'Handoff Strategies', 'Interference (CCI & ACI)'],
        description: 'Exhaustive university sequence on cellular hexagonal geometry, frequency reuse calculations, co-channel interference ratio Q, and umbrella cell configurations.',
        url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRg1q2gGzX9V7v2y3W_z4L5m',
        lectureKey: 'cs702wmc-neso-cellular-full'
    },
    {
        semester: 7,
        subject: 'cs702-wmc',
        subjectCode: 'CS-702-WMC',
        subjectLabel: 'Wireless & Mobile Computing',
        title: 'Wireless Communication & Mobile Computing Course',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Exam Prep Series',
        topics: ['GSM Architecture', 'Mobile IP', 'Snoop TCP & Indirect TCP', 'WAP Architecture', '4G/5G Networks'],
        description: 'High-yield university lectures covering GSM network switching subsystems (HLR/VLR/AUC), Mobile IP triangular routing, and wireless TCP optimization.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiHzm9lqU8W_v2_fJ6T9Qo8m',
        lectureKey: 'cs702wmc-gate-smashers-wmc'
    },
    {
        semester: 7,
        subject: 'cs702-wmc',
        subjectCode: 'CS-702-WMC',
        subjectLabel: 'Wireless & Mobile Computing',
        title: 'Cellular Frequency Reuse & Cluster Size N Derivation',
        lecturer: 'Tutorials Point',
        type: 'video',
        typeLabel: 'Mathematical Derivation',
        topics: ['Cluster Size N = i^2 + ij + j^2', 'Reuse Ratio Q = D/R = sqrt(3N)', 'SIR Calculation in dB', 'Co-channel Distance'],
        description: 'Complete mathematical derivation of the hexagonal tessellation equation N = i^2 + ij + j^2, co-channel reuse ratio Q = sqrt(3N), and worst-case SIR equations.',
        url: 'https://www.youtube.com/watch?v=f7Bq5oV_9e4',
        lectureKey: 'cs702wmc-cluster-size-derivation'
    },
    {
        semester: 7,
        subject: 'cs702-wmc',
        subjectCode: 'CS-702-WMC',
        subjectLabel: 'Wireless & Mobile Computing',
        title: 'GSM Architecture & Subsystem Components (BSS, NSS, OSS)',
        lecturer: 'Neso Academy',
        type: 'video',
        typeLabel: 'Core Architecture',
        topics: ['Base Station Subsystem (BTS, BSC)', 'Network Switching Subsystem (MSC, HLR, VLR)', 'EIR & AUC', 'Air Interface Um'],
        description: 'Clear architectural breakdown of GSM functional blocks: Mobile Station (MS), Base Transceiver Station (BTS), Base Station Controller (BSC), MSC, HLR, and VLR registers.',
        url: 'https://www.youtube.com/watch?v=0O2J5gH1p38',
        lectureKey: 'cs702wmc-gsm-architecture'
    },
    {
        semester: 7,
        subject: 'cs702-wmc',
        subjectCode: 'CS-702-WMC',
        subjectLabel: 'Wireless & Mobile Computing',
        title: 'Mobile IP: Agent Discovery, Registration & Care-of Address',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Protocol Mechanism',
        topics: ['Home Agent (HA)', 'Foreign Agent (FA)', 'Care-of Address (CoA)', 'IP Tunneling', 'Triangular Routing Problem'],
        description: 'Step-by-step walkthrough of Mobile IP registration, IP-in-IP encapsulation tunneling, reverse tunneling, and eliminating triangular routing inefficiencies.',
        url: 'https://www.youtube.com/watch?v=v8X_J8P2s4c',
        lectureKey: 'cs702wmc-mobile-ip-guide'
    },

    // --- CS-703: Cryptography & Info Security (CIS) ---
    {
        semester: 7,
        subject: 'cs703',
        subjectCode: 'CS-703',
        subjectLabel: 'Cryptography & Info Security',
        title: 'Diffie-Hellman Key Exchange & Discrete Logarithm Problem',
        lecturer: 'Computerphile (Dr. Mike Pound)',
        type: 'video',
        typeLabel: 'Cryptographic Masterclass',
        topics: ['Primitive Roots', 'Discrete Logarithm', 'Public Key Negotiation', 'Man-In-The-Middle Attack', 'ECDH'],
        description: 'Internationally acclaimed visual explanation of the Diffie-Hellman protocol, modular exponentiation math, and why computing discrete logarithms is computationally intractable.',
        url: 'https://www.youtube.com/watch?v=NmM9HA2MQGI',
        lectureKey: 'cs703-diffie-hellman-guide'
    },
    {
        semester: 7,
        subject: 'cs703',
        subjectCode: 'CS-703',
        subjectLabel: 'Cryptography & Info Security',
        title: 'Cryptography & Network Security Complete Course',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['Classical Ciphers', 'DES & AES Feistel Networks', 'RSA Numericals', 'Diffie-Hellman', 'Digital Signatures', 'X.509 PKI'],
        description: 'Complete university curriculum covering cryptographic algorithms, substitution/permutation ciphers, round transformations, HMACs, and certificate authority hierarchies.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiHcmS4i14bI0VrMbZTUvlTa',
        lectureKey: 'cs703-gate-smashers-cis'
    },
    {
        semester: 7,
        subject: 'cs703',
        subjectCode: 'CS-703',
        subjectLabel: 'Cryptography & Info Security',
        title: 'Cryptography & Information Security Playlist',
        lecturer: 'Neso Academy',
        type: 'playlist',
        typeLabel: 'Structured Course',
        topics: ['Security Goals (CIA Triad)', 'Cryptanalysis Attacks', 'Block Cipher Modes', 'Hash Functions (MD5, SHA)', 'Kerberos'],
        description: 'Formal mathematical and engineering walkthrough of modern cryptographic protocols, authentication servers (Kerberos), and transport layer security.',
        url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRh6hN_V0v9A1p7L3_P9pY8v',
        lectureKey: 'cs703-neso-cryptography'
    },
    {
        semester: 7,
        subject: 'cs703',
        subjectCode: 'CS-703',
        subjectLabel: 'Cryptography & Info Security',
        title: 'How TLS 1.3 & Digital Certificates (PKI) Work',
        lecturer: 'Computerphile',
        type: 'video',
        typeLabel: 'Systems Deep Dive',
        topics: ['TLS 1.3 Handshake', 'Zero-Round Trip Time (0-RTT)', 'Certificate Authorities (CA)', 'Chain of Trust', 'Session Keys'],
        description: 'Clear, modern explanation of cryptographic handshakes in TLS 1.3, ephemeral Diffie-Hellman key exchanges (ECDHE), and public key infrastructure certificate chains.',
        url: 'https://www.youtube.com/watch?v=0pcp_tVv-L4',
        lectureKey: 'cs703-tls-handshake-pki'
    },
    {
        semester: 7,
        subject: 'cs703',
        subjectCode: 'CS-703',
        subjectLabel: 'Cryptography & Info Security',
        title: 'Hash Functions, SHA-256 & Avalanche Effect',
        lecturer: 'Computerphile',
        type: 'video',
        typeLabel: 'Core Cryptographic Primitive',
        topics: ['One-Way Property', 'Collision Resistance', 'Merkle-Damgard Construction', 'Avalanche Effect'],
        description: 'Comprehensive breakdown of cryptographic hashing, bit shifting, message schedules, padding bytes, and the mathematical proof of the birthday paradox collision resistance.',
        url: 'https://www.youtube.com/watch?v=DMtFhACPnTY',
        lectureKey: 'cs703-hash-functions-sha'
    },

    // --- CS-703-DM: Disaster Management ---
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'Disaster Management Complete Course',
        lecturer: 'NPTEL / IIT Roorkee',
        type: 'playlist',
        typeLabel: 'Premier University Playlist',
        topics: ['Natural & Anthropogenic Hazards', 'Vulnerability Assessment', 'Disaster Risk Reduction', 'Sendai Framework', 'NDMA Act 2005'],
        description: 'Rigorous national curriculum delivered by IIT professors covering geological, hydro-meteorological, and technological hazards, along with disaster governance institutions.',
        url: 'https://www.youtube.com/playlist?list=PLbRMhDVUMngcfG5wKjP_l4h7Pz5W1o7kY',
        lectureKey: 'cs703dm-nptel-full-course'
    },
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'Hazard, Vulnerability & Risk Formulation with Disaster Cycle',
        lecturer: 'UPSC Pathshala',
        type: 'video',
        typeLabel: 'Core Theory & Framework',
        topics: ['Risk = (H x V) / Capacity', '4 Phases of Disaster Cycle', 'Mitigation & Preparedness', 'Response & Recovery'],
        description: 'Comprehensive breakdown of quantitative disaster risk formulas, structural vs non-structural mitigation, the Golden 72 Hours response window, and reconstruction.',
        url: 'https://www.youtube.com/watch?v=x7K4f9kL1pM',
        lectureKey: 'cs703dm-hazard-vulnerability-risk'
    },
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'Remote Sensing & GIS in Disaster Risk Reduction',
        lecturer: 'UN-SPIDER',
        type: 'video',
        typeLabel: 'Technology Integration',
        topics: ['Satellite Imagery', 'GIS Spatial Inundation Mapping', 'Early Warning Systems', 'Damage Assessment'],
        description: 'United Nations spatial informatics lecture on applying satellite remote sensing, multi-spectral sensors, and GIS overlays for flood, cyclone, and seismic crisis mapping.',
        url: 'https://www.youtube.com/watch?v=8w1P8o_w8v4',
        lectureKey: 'cs703dm-remote-sensing-gis'
    },
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'IT Disaster Recovery: RPO, RTO & High Availability Architecture',
        lecturer: 'Simplilearn',
        type: 'video',
        typeLabel: 'Engineering Masterclass',
        topics: ['Recovery Time Objective (RTO)', 'Recovery Point Objective (RPO)', 'Cold vs Warm vs Hot DR Sites', 'Business Continuity Planning (BCP)'],
        description: 'Engineering guide to enterprise data center disaster recovery, database replication lag, active-passive failover clusters, and business continuity management.',
        url: 'https://www.youtube.com/watch?v=2T5v_K6vP5A',
        lectureKey: 'cs703dm-it-disaster-recovery'
    },
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'Sendai Framework & Disaster Management Act 2005 Governance',
        lecturer: 'Vision IAS',
        type: 'video',
        typeLabel: 'Policy & Governance',
        topics: ['Sendai 4 Priorities for Action', 'Build Back Better', 'NDMA, SDMA, DDMA Three-Tier Structure', 'NDRF Response'],
        description: 'Exam-focused analysis of international disaster treaties, the Sendai Framework (2015-2030), India\'s Disaster Management Act 2005, and national disaster response forces.',
        url: 'https://www.youtube.com/watch?v=vB2j1g7v7sI',
        lectureKey: 'cs703dm-sendai-ndma-act'
    }
];
