window.lectureLibrary = [
    /* =========================================================================
       SEMESTER 5 SUBJECTS
       ========================================================================= */

    // --- CS-501: Theory of Computation (TOC) ---
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'TOC Full Course for Semester Exams & GATE',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Exam Prep Series',
        topics: ['DFA Minimization', 'Myhill-Nerode', 'Chomsky Hierarchy', 'Pumping Lemma', 'Undecidability'],
        description: 'University-focused masterclass covering state minimization, equivalent states, pumping lemma proofs, and context-free reductions.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiFM9Lj5G9G_76adtyb4ef7i',
        lectureKey: 'cs501-gate-smashers-toc'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'Introduction to Theory of Computation & Automata',
        lecturer: 'MIT OpenCourseWare',
        type: 'video',
        typeLabel: 'Foundational Theory',
        topics: ['Computational Models', 'State Machines', 'Formal Grammars'],
        description: 'Rigorous introduction to formal languages, automata theory, and the computational hierarchy.',
        url: 'https://www.youtube.com/watch?v=58N2N7zJGrQ',
        lectureKey: 'cs501-theory-intro'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'DFA State Minimization Step-by-Step Algorithm',
        lecturer: 'Knowledge Gate',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['Table Filling Method', 'Partitioning Algorithm', 'Equivalence Classes', 'Dead States'],
        description: 'Complete solved example showing how to eliminate redundant states using equivalence partitions and Myhill-Nerode table filling.',
        url: 'https://www.youtube.com/watch?v=0XaGAkY09Wc',
        lectureKey: 'cs501-dfa-minimization-guide'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'NFA to DFA Subset Construction Algorithm',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['Subset Construction', 'Epsilon Closures', 'Power Set States', 'Dead States'],
        description: 'Step-by-step conversion of non-deterministic finite automata to equivalent deterministic state machines.',
        url: 'https://www.youtube.com/watch?v=--CSVsFIDng',
        lectureKey: 'cs501-nfa-to-dfa'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'Turing Machines Explained & Halting Problem',
        lecturer: 'Computerphile',
        type: 'video',
        typeLabel: 'Theory Deep Dive',
        topics: ['Tape Head', 'Transition Function', 'Decidability', 'Halting Problem'],
        description: 'Intuitive and visual guide to universal Turing machines, recursive languages, and computational limits.',
        url: 'https://www.youtube.com/watch?v=dNRDvLACg5Q',
        lectureKey: 'cs501-turing-machines'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'Mastering PDA to CFG Conversion Step-by-Step',
        lecturer: 'Learning Lab with Yograj',
        type: 'video',
        typeLabel: 'Solved Derivation',
        topics: ['PDA to CFG Algorithm', 'Triplets [q, X, p]', 'Production Rules', 'Empty Stack Acceptance'],
        description: 'Systematic blackboard derivation converting pushdown automata transitions δ(q, a, Z) into context-free grammar production rules with solved exam numericals.',
        url: 'https://www.youtube.com/watch?v=fWDJrWw1YCU',
        lectureKey: 'cs501-yograj-pda-to-cfg'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: '1001 Sequence Detector: State Diagram & Transition Table',
        lecturer: 'Learning Lab with Yograj',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['1001 Sequence Detection', 'Mealy vs Moore Machine', 'State Minimization', 'Overlapping Patterns'],
        description: 'Exam and GATE-focused design of a 1001 pattern sequence detector, state transition diagrams, overlapping bit tracking, and state table construction.',
        url: 'https://www.youtube.com/watch?v=xvMpe0sKrbg',
        lectureKey: 'cs501-yograj-sequence-detector'
    },

    // --- CS-502: Database Management Systems (DBMS) ---
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'SQL & Database Design Course',
        lecturer: 'freeCodeCamp',
        type: 'video',
        typeLabel: 'Full Course Masterclass',
        topics: ['Relational Model', 'SQL Queries', 'Foreign Keys', 'Indexes', 'Schema Design'],
        description: 'Comprehensive 4-hour course covering database architecture, relational algebra, SQL DDL/DML, and schema normalization.',
        url: 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
        lectureKey: 'cs502-sql-course-fcc'
    },
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'Database Design Course - Storage, Normalization & ER Diagrams',
        lecturer: 'Caleb Curry',
        type: 'video',
        typeLabel: 'Architecture Masterclass',
        topics: ['ER Modeling', 'Entity-Relationship', 'Cardinality', 'Normalization 1NF-BCNF'],
        description: 'Detailed conceptual walkthrough of relational database design, identifying candidate keys, and preventing anomaly risks.',
        url: 'https://www.youtube.com/watch?v=ztHopE5Wnpc',
        lectureKey: 'cs502-db-design-caleb'
    },
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'DBMS Full Course - Complete University Tutorial',
        lecturer: 'Edureka',
        type: 'video',
        typeLabel: 'University Curriculum',
        topics: ['3-Tier Architecture', 'Transaction Processing', 'ACID Properties', 'Concurreny Control'],
        description: 'Thorough lecture covering database storage engines, B+ Tree indexing, serializability, lock-based protocols, and deadlock detection.',
        url: 'https://www.youtube.com/watch?v=T7AxM7Vqvaw',
        lectureKey: 'cs502-edureka-dbms'
    },
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'Database Normalization: 1NF, 2NF, 3NF & BCNF with Solved Examples',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['Functional Dependencies', 'Prime Attributes', '1NF/2NF/3NF', 'BCNF Decomposition'],
        description: 'Master functional dependencies, closure sets, canonical covers, lossless join decomposition, and dependency preservation.',
        url: 'https://www.youtube.com/watch?v=GFQaEYEc8_8',
        lectureKey: 'cs502-normalization-solved'
    },
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'Relational Algebra Operators in DBMS',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Core Operators',
        topics: ['Selection & Projection', 'Cartesian Product', 'Natural Join', 'Division Operator'],
        description: 'Complete breakdown of fundamental and extended relational algebra operators with high-scoring university numericals.',
        url: 'https://www.youtube.com/watch?v=4YilEjkNPrQ',
        lectureKey: 'cs502-relational-algebra'
    },

    // --- CS-503: Data Analytics ---
    {
        semester: 5,
        subject: 'cs503',
        subjectCode: 'CS-503',
        subjectLabel: 'Data Analytics',
        title: 'Data Analysis with Python Full Course',
        lecturer: 'freeCodeCamp',
        type: 'video',
        typeLabel: 'Hands-on Course',
        topics: ['NumPy', 'Pandas DataFrames', 'Data Cleaning', 'Statistical Aggregation', 'Matplotlib'],
        description: 'Extensive hands-on tutorial on exploratory data analysis (EDA), data parsing, feature handling, and statistical modeling.',
        url: 'https://www.youtube.com/watch?v=r-uOLxNrNk8',
        lectureKey: 'cs503-data-analysis-python'
    },
    {
        semester: 5,
        subject: 'cs503',
        subjectCode: 'CS-503',
        subjectLabel: 'Data Analytics',
        title: 'Statistics for Data Science & Business Analytics',
        lecturer: '365 Data Science',
        type: 'video',
        typeLabel: 'Theory & Foundations',
        topics: ['Probability Distributions', 'Central Limit Theorem', 'Variance & Covariance', 'Hypothesis Testing'],
        description: 'Core statistical foundations covering normal/binomial distributions, confidence intervals, p-values, and regression analysis.',
        url: 'https://www.youtube.com/watch?v=xxpc-HPKN28',
        lectureKey: 'cs503-stats-data-science'
    },
    {
        semester: 5,
        subject: 'cs503',
        subjectCode: 'CS-503',
        subjectLabel: 'Data Analytics',
        title: 'Hypothesis Testing Full Concept: Z-Test, T-Test & Chi-Square',
        lecturer: 'Zedstatistics',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['Null vs Alternative Hypothesis', 'Type I & II Errors', 'Z-Test vs T-Test', 'P-value Interpretation'],
        description: 'Intuitive visual walkthrough of hypothesis testing formulations, critical regions, and significance level derivations.',
        url: 'https://www.youtube.com/watch?v=0oc49DyA3hU',
        lectureKey: 'cs503-hypothesis-testing'
    },

    // --- CS-503-CS: Cyber Security ---
    {
        semester: 5,
        subject: 'cs503-cs',
        subjectCode: 'CS-503-CS',
        subjectLabel: 'Cyber Security',
        title: 'Cyber Security Full Course for Beginners',
        lecturer: 'freeCodeCamp',
        type: 'video',
        typeLabel: 'Comprehensive Course',
        topics: ['Threat Modeling', 'Network Security', 'Firewalls', 'Malware Types', 'Access Control'],
        description: 'Foundational masterclass covering defense-in-depth, reconnaissance, port scanning, intrusion detection systems (IDS), and encryption.',
        url: 'https://www.youtube.com/watch?v=U_P23SqJaDc',
        lectureKey: 'cs503cs-cyber-security-fcc'
    },
    {
        semester: 5,
        subject: 'cs503-cs',
        subjectCode: 'CS-503-CS',
        subjectLabel: 'Cyber Security',
        title: 'Cyber Security in 7 Hours - Complete University Prep',
        lecturer: 'Edureka',
        type: 'video',
        typeLabel: 'Full Curriculum',
        topics: ['CIA Triad', 'Cryptography', 'Penetration Testing', 'SIEM', 'Incident Response'],
        description: 'Seven-hour syllabus breakdown detailing confidentiality, integrity, availability, symmetrical ciphers, and security operations center workflows.',
        url: 'https://www.youtube.com/watch?v=inWWhr5tnEA',
        lectureKey: 'cs503cs-edureka-7hr'
    },
    {
        semester: 5,
        subject: 'cs503-cs',
        subjectCode: 'CS-503-CS',
        subjectLabel: 'Cyber Security',
        title: 'Public Key Cryptography & RSA Algorithm In-Depth',
        lecturer: 'Art of the Problem',
        type: 'video',
        typeLabel: 'Math & Primality',
        topics: ['Euler Totient Function', 'Trapdoor Functions', 'Modular Inverses', 'Prime Generation'],
        description: 'Visual mathematical breakdown explaining why public-key cryptography works and how trapdoor functions protect asymmetric communications.',
        url: 'https://www.youtube.com/watch?v=AQDCe585Lnc',
        lectureKey: 'cs503cs-rsa-trapdoor'
    },
    {
        semester: 5,
        subject: 'cs503-cs',
        subjectCode: 'CS-503-CS',
        subjectLabel: 'Cyber Security',
        title: 'Cyber Law and Ethics Complete Series (IT Act 2000, Jurisdiction & Contracts)',
        lecturer: 'Learning Lab with Yograj',
        type: 'playlist',
        typeLabel: 'University Syllabus Series',
        topics: ['IT Act 2000', 'Cyber Torts', 'E-Commerce & Online Contracts', 'Jurisdiction in Cyberspace', 'Domain Name Disputes'],
        description: 'Structured 8-part lecture series detailing Indian IT Act 2000, civil/criminal cyber jurisdiction, digital contracts, and online dispute resolution.',
        url: 'https://www.youtube.com/playlist?list=PL424dCM7s48l2tCev9s2v7ZtmjZaPYxYI',
        lectureKey: 'cs503cs-yograj-cyber-law-ethics'
    },

    // --- CS-504: Web Technology ---
    {
        semester: 5,
        subject: 'cs504',
        subjectCode: 'CS-504',
        subjectLabel: 'Web Technology',
        title: 'HTML & CSS Full Course - Web Development Fundamentals',
        lecturer: 'SuperSimpleDev',
        type: 'video',
        typeLabel: 'Front-End Masterclass',
        topics: ['HTML5 Semantics', 'CSS Flexbox', 'CSS Grid', 'Box Model', 'Responsive Web Design'],
        description: 'Step-by-step masterclass covering modern HTML5 document architecture, CSS layout mechanisms, media queries, and responsive viewports.',
        url: 'https://www.youtube.com/watch?v=mU6anWqZJcc',
        lectureKey: 'cs504-html-css-master'
    },
    {
        semester: 5,
        subject: 'cs504',
        subjectCode: 'CS-504',
        subjectLabel: 'Web Technology',
        title: 'JavaScript Tutorial for Beginners - Modern ES6+ Scripting',
        lecturer: 'Programming with Mosh',
        type: 'video',
        typeLabel: 'Core Language',
        topics: ['DOM Manipulation', 'Event Loop', 'Promises & Async/Await', 'Objects & Prototypes'],
        description: 'Essential JavaScript primer covering synchronous execution, DOM tree mutations, event listeners, and asynchronous HTTP fetch requests.',
        url: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
        lectureKey: 'cs504-js-mosh'
    },
    {
        semester: 5,
        subject: 'cs504',
        subjectCode: 'CS-504',
        subjectLabel: 'Web Technology',
        title: 'PHP for Beginners - Server-Side Scripting & Database Integration',
        lecturer: 'Traversy Media',
        type: 'video',
        typeLabel: 'Back-End Fundamentals',
        topics: ['PHP Syntax', 'Superglobals ($_POST, $_GET)', 'Sessions & Cookies', 'PDO MySQL'],
        description: 'Complete introductory walkthrough of server-side page lifecycle, form validation, session persistence, and database connectivity.',
        url: 'https://www.youtube.com/watch?v=BUCiSSyIGGU',
        lectureKey: 'cs504-php-traversy'
    },
    {
        semester: 5,
        subject: 'cs504',
        subjectCode: 'CS-504',
        subjectLabel: 'Web Technology',
        title: 'HTTP Crash Course & RESTful Web APIs',
        lecturer: 'Traversy Media',
        type: 'video',
        typeLabel: 'Network Protocol',
        topics: ['HTTP Verbs (GET/POST/PUT/DELETE)', 'Status Codes (2xx, 4xx, 5xx)', 'Headers', 'REST Constraints'],
        description: 'Essential network architecture lecture covering stateless HTTP message structure, headers, cache control, and RESTful resource routing.',
        url: 'https://www.youtube.com/watch?v=iYM2zFP3Zn0',
        lectureKey: 'cs504-http-rest-crash'
    },

    /* =========================================================================
       SEMESTER 6 SUBJECTS
       ========================================================================= */

    // --- CS-601: Machine Learning ---
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Machine Learning Course for Beginners',
        lecturer: 'freeCodeCamp',
        type: 'video',
        typeLabel: 'Complete Masterclass',
        topics: ['Supervised Learning', 'Linear & Logistic Regression', 'KNN', 'Decision Trees', 'Loss Functions'],
        description: 'Foundational introduction to machine learning paradigms, cost functions, gradient descent optimization, and evaluation metrics.',
        url: 'https://www.youtube.com/watch?v=NWONeJKn6kc',
        lectureKey: 'cs601-ml-beginners-fcc'
    },
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Support Vector Machines (SVM) & Kernel Trick Clearly Explained',
        lecturer: 'StatQuest (Josh Starmer)',
        type: 'video',
        typeLabel: 'Algorithm Deep Dive',
        topics: ['Maximal Margin Classifier', 'Support Vectors', 'Soft Margin (C)', 'Radial Basis Function (RBF) Kernel'],
        description: 'Intuitive mathematical breakdown of hyperplane margins, Lagrange multipliers, and high-dimensional kernel transformations.',
        url: 'https://www.youtube.com/watch?v=efR1C6CvhmE',
        lectureKey: 'cs601-svm-statquest'
    },
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Neural Networks & Deep Learning Visual Series',
        lecturer: '3Blue1Brown (Grant Sanderson)',
        type: 'video',
        typeLabel: 'Visual Mathematics',
        topics: ['Perceptron', 'Activation Functions (ReLU, Sigmoid)', 'Gradient Descent', 'Backpropagation Calculus'],
        description: 'Visual masterpiece explaining weights, biases, cost landscapes, partial derivatives, and multi-layer chain rule backpropagation.',
        url: 'https://www.youtube.com/watch?v=aircAruvnKk',
        lectureKey: 'cs601-neural-networks-3b1b'
    },
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Decision Trees & Gini Impurity Clearly Explained',
        lecturer: 'StatQuest',
        type: 'video',
        typeLabel: 'Algorithm Deep Dive',
        topics: ['Gini Impurity', 'Information Gain', 'Entropy', 'Overfitting & Pruning'],
        description: 'Step-by-step numerical breakdown showing how decision trees calculate candidate splits and prune decision nodes.',
        url: 'https://www.youtube.com/watch?v=7VeUPuFGJHk',
        lectureKey: 'cs601-decision-trees-statquest'
    },

    // --- CS-602: Computer Networks ---
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Computer Networks 21-Lecture Full Playlist (Error Control, OSI, IPv4, TCP/UDP)',
        lecturer: 'Learning Lab with Yograj (Yograj Sharma)',
        type: 'playlist',
        typeLabel: 'University Syllabus Series',
        topics: ['Error Control & CRC', 'Checksum Derivations', 'OSI 7 Layers', 'IPv4 Fragmentation & Offsets', 'TCP / UDP Headers', 'ARP / RARP', 'DNS & HTTP'],
        description: 'Comprehensive 21-part university lecture series covering CRC polynomials, Checksum math, OSI protocol stacks, IPv4 datagram fragmentation, and transport headers.',
        url: 'https://www.youtube.com/playlist?list=PL424dCM7s48neYqR5yL2P9uxlXW3DQSJq',
        lectureKey: 'cs602-yograj-networks-playlist'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Cyclic Redundancy Check (CRC) Solved Example & Error Control',
        lecturer: 'Learning Lab with Yograj',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['CRC Generator Polynomial G(x)', 'Modulo-2 Binary Division', 'Syndrome & Remainder Padding', 'Bit Error Detection'],
        description: 'Blackboard solved numerical calculating transmitted codeword with generator polynomial, CRC remainder zero-padding, and receiver bit-error verification.',
        url: 'https://www.youtube.com/watch?v=dSND1fgx6g8&list=PL424dCM7s48neYqR5yL2P9uxlXW3DQSJq',
        lectureKey: 'cs602-yograj-crc-example'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Internet Checksum Calculation & 1s Complement Math',
        lecturer: 'Learning Lab with Yograj',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['1s Complement Addition', 'End-Around Carry Wraparound', 'Bit Inversion', 'Checksum Verification Check'],
        description: 'Practical step-by-step calculation of Internet checksums: 16-bit word addition, folding end-around carry, bit inversion, and receiver validation.',
        url: 'https://www.youtube.com/watch?v=N8IJ2uvGWiE&list=PL424dCM7s48neYqR5yL2P9uxlXW3DQSJq',
        lectureKey: 'cs602-yograj-checksum'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'IPv4 Fragmentation & Reassembly: MTU & Offset Numericals',
        lecturer: 'Learning Lab with Yograj',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['Maximum Transmission Unit (MTU)', 'Fragment Offset (Divided by 8)', 'More Fragments (MF) Flag', 'Dont Fragment (DF) Flag'],
        description: 'Exam-focused numerical walkthrough calculating fragment payloads, 8-byte scale fragment offsets, and flag bits when MTU is smaller than total datagram length.',
        url: 'https://www.youtube.com/watch?v=TzDh72hG4J8&list=PL424dCM7s48neYqR5yL2P9uxlXW3DQSJq',
        lectureKey: 'cs602-yograj-ipv4-fragmentation'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'TCP Header Format & Control Flags (URG, ACK, PSH, RST, SYN, FIN)',
        lecturer: 'Learning Lab with Yograj',
        type: 'video',
        typeLabel: 'Protocol Architecture',
        topics: ['32-bit Sequence & ACK Numbers', 'Header Length (HLEN)', '6 Control Bit Flags', 'Receive Window & Urgent Pointer'],
        description: 'Complete breakdown of the 20-byte base TCP header, detailing byte stream sequence ordering, acknowledgment mechanisms, sliding window advertisements, and connection handshake flags.',
        url: 'https://www.youtube.com/watch?v=6XYREH7lkog&list=PL424dCM7s48neYqR5yL2P9uxlXW3DQSJq',
        lectureKey: 'cs602-yograj-tcp-header'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Computer Networking Full Course - Network Direction',
        lecturer: 'Network Direction',
        type: 'video',
        typeLabel: 'Full Course Masterclass',
        topics: ['OSI 7-Layer Model', 'TCP/IP Architecture', 'Routing Protocols (OSPF, BGP)', 'Switching & VLANs'],
        description: 'Comprehensive network architecture course detailing physical signaling, MAC framing, IP routing, TCP flow control, and application sockets.',
        url: 'https://www.youtube.com/watch?v=IPvYjXCsTg8',
        lectureKey: 'cs602-network-direction-full'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Subnetting Mastery - CIDR & Variable Length Subnet Masking (VLSM)',
        lecturer: 'Practical Networking',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['CIDR Notation (/24, /28)', 'Subnet Masks', 'Network vs Broadcast Address', 'Host Capacity Math'],
        description: 'High-speed binary and fast-math tutorial on calculating network addresses, first/last usable IP addresses, and custom subnets.',
        url: 'https://www.youtube.com/watch?v=ecCuyq-Wprc',
        lectureKey: 'cs602-subnetting-mastery'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'TCP/IP & The Internet Protocols Explained',
        lecturer: 'Computerphile (Dr. Mike Pound)',
        type: 'video',
        typeLabel: 'Protocol Architecture',
        topics: ['3-Way Handshake (SYN, SYN-ACK, ACK)', 'Sequence Numbers', 'Sliding Window', 'Congestion Control'],
        description: 'In-depth protocol walkthrough explaining TCP reliability guarantees, packet retransmissions, window sizing, and packet headers.',
        url: 'https://www.youtube.com/watch?v=PpsEaqJV_A0',
        lectureKey: 'cs602-tcp-handshake-computerphile'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'How The Internet Works - Global Packet Routing & BGP',
        lecturer: 'Aaron',
        type: 'video',
        typeLabel: 'System Infrastructure',
        topics: ['Undersea Cables', 'DNS Hierarchy', 'BGP Autonomous Systems', 'Tier-1 ISPs'],
        description: 'Visual system-level overview of undersea fiber optics, Border Gateway Protocol (BGP), Tier-1 transit backbones, and internet exchange points.',
        url: 'https://www.youtube.com/watch?v=7_LPdttKXPc',
        lectureKey: 'cs602-how-internet-works'
    },

    // --- CS-603: Compiler Design ---
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'Compiler Design University Exam Series',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Exam Prep Series',
        topics: ['Left Recursion Elimination', 'Left Factoring', 'LR(0) & SLR(1)', 'LALR(1)', 'Three-Address Code', 'DAG'],
        description: 'Concise, high-scoring university lectures on eliminating immediate and indirect left recursion, canonical collections of LR items, and syntax directed translations.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiEKtKSIHYusizkESC42diyc',
        lectureKey: 'cs603-gate-smashers-compiler'
    },
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'What Is a Compiler? Architecture & 6 Phases Overview',
        lecturer: 'Neso Academy',
        type: 'video',
        typeLabel: 'Concept Primer',
        topics: ['Compiler vs Interpreter', 'Analysis & Synthesis Phases', 'Symbol Table', 'Error Handler'],
        description: 'Foundational lecture introducing the 6 phases of a compiler: Lexical, Syntax, Semantic, Intermediate Code, Code Optimizer, and Target Code Generator.',
        url: 'https://www.youtube.com/watch?v=5ZmFlxrNaN8',
        lectureKey: 'cs603-compiler-intro'
    },
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'Compiler Design Full Lecture Series',
        lecturer: 'Neso Academy',
        type: 'playlist',
        typeLabel: 'Comprehensive Course',
        topics: ['Lexical Analysis', 'Parsing Theory', 'Shift-Reduce', 'Operator Precedence', 'Intermediate Representation'],
        description: 'Complete curriculum coverage including tokenization, First and Follow set calculations, LL(1) parsing tables, and quadruples/triples.',
        url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRjT3oJxFXRgjPNzeS-LFY-q',
        lectureKey: 'cs603-neso-compiler-full'
    },
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'Introduction to Compiler Design & Parsing Theory',
        lecturer: 'Alex Aiken (Stanford)',
        type: 'video',
        typeLabel: 'Academic Masterclass',
        topics: ['Context-Free Grammars', 'Abstract Syntax Trees (AST)', 'Type Checking', 'Code Generation'],
        description: 'Academic deep-dive into compiler frontends, regular expressions vs grammars, and syntax-directed semantic analysis.',
        url: 'https://www.youtube.com/watch?v=Qkwj65l_96I',
        lectureKey: 'cs603-stanford-compiler'
    },

    // --- CS-603-CG: Computer Graphics ---
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: 'OpenGL & 3D Computer Graphics Pipeline',
        lecturer: 'The Cherno',
        type: 'playlist',
        typeLabel: 'Engineering Deep Dive',
        topics: ['Vertex Buffers (VBO)', 'Index Buffers (IBO)', 'Shaders (GLSL)', 'Model-View-Projection (MVP)', 'Textures'],
        description: 'Industry-standard graphics programming series covering GPU architectures, vertex/fragment shaders, affine matrix transforms, and depth testing.',
        url: 'https://www.youtube.com/playlist?list=PLlrATfBNZ98foTJPJ_Ev03o2oq3-GGOS2',
        lectureKey: 'cs603cg-the-cherno-opengl'
    },
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: 'Modern OpenGL 3D Game Programming',
        lecturer: 'The Cherno',
        type: 'video',
        typeLabel: 'Graphics Architecture',
        topics: ['Rendering Pipeline', 'Rasterization', 'Framebuffers', 'Uniform Buffers'],
        description: 'Practical guide to establishing 3D rendering context, compiling shaders, and manipulating vertex attribute pointers.',
        url: 'https://www.youtube.com/watch?v=W3gAzLwfIP0',
        lectureKey: 'cs603cg-opengl-intro'
    },
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: 'Bresenham Line Drawing Algorithm with Derivation & Solved Numerical',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['Decision Parameter (P)', 'Integer-Only Arithmetic', 'Slope Increments', 'Rasterization'],
        description: 'Full mathematical derivation of Bresenham line generation avoiding floating-point multiplication with step-by-step pixel plotting.',
        url: 'https://www.youtube.com/watch?v=RGB-wlatStc',
        lectureKey: 'cs603cg-bresenham-line'
    },
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: '2D & 3D Transformations: Translation, Scaling, Rotation & Homogeneous Coordinates',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['Homogeneous Coordinates', 'Composite Matrix', 'Rotation about Arbitrary Point', 'Shearing & Reflection'],
        description: 'Essential university syllabus numericals on affine transformation matrices, matrix concatenation order, and rotation pivoting.',
        url: 'https://www.youtube.com/watch?v=kYB8IZa5AuE',
        lectureKey: 'cs603cg-transforms-math'
    },

    // --- CS-604: Project Management / Software Engineering ---
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'Software Engineering Complete University Course',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Exam Prep Series',
        topics: ['SRS Documentation', 'Function Point Analysis', 'Cyclomatic Complexity', 'Coupling & Cohesion', 'Black/White Box Testing'],
        description: 'Exam-focused tutorials on software requirements specifications (SRS), McCabe cyclomatic complexity, coupling vs cohesion metrics, and verification vs validation.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiEed7SKZBnC6ypFDWYLRvB2',
        lectureKey: 'cs604-gate-smashers-se'
    },
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'Software Engineering & Project Management Playlist',
        lecturer: '5 Minutes Engineering',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['SDLC Models', 'Agile & Scrum', 'COCOMO Model', 'CPM & PERT', 'Risk Management', 'Software Testing'],
        description: 'University syllabus covered in crisp, high-yield videos on Waterfall, Spiral, Agile Scrum ceremonies, critical path scheduling, and risk mitigation strategies.',
        url: 'https://www.youtube.com/playlist?list=PLYwpaL_SFmcCB7zUM0YSDR-1mM4KoiyLM',
        lectureKey: 'cs604-5min-pm-playlist'
    },
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'Agile & Scrum Framework Explained in 10 Minutes',
        lecturer: 'Development That Pays',
        type: 'video',
        typeLabel: 'Industry Methodology',
        topics: ['Sprints', 'Product Backlog', 'User Stories', 'Daily Standup', 'Sprint Review & Retrospective'],
        description: 'Practical walkthrough of agile methodology, scrum artifacts, ceremony pacing, and velocity estimation.',
        url: 'https://www.youtube.com/watch?v=9TycLR0TqFA',
        lectureKey: 'cs604-agile-scrum'
    },
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'Git & GitHub Tutorial for Project Collaboration',
        lecturer: 'freeCodeCamp',
        type: 'video',
        typeLabel: 'Engineering Tools',
        topics: ['Version Control', 'Branching Strategies', 'Pull Requests', 'Merge Conflicts', 'Rebase'],
        description: 'Hands-on tutorial on distributed version control systems, feature branch workflows, commit hygiene, and code review lifecycles.',
        url: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
        lectureKey: 'cs604-git-github-fcc'
    },

    /* =========================================================================
       SEMESTER 7 SUBJECTS
       ========================================================================= */

    // --- CS-701: Software Architectures ---
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: 'Design Patterns & Architectural Styles',
        lecturer: 'Derek Banas',
        type: 'playlist',
        typeLabel: 'Full Patterns Course',
        topics: ['Creational Patterns', 'Structural Patterns', 'Behavioral Patterns', 'MVC & Observer', 'Adapter & Facade'],
        description: 'Comprehensive video sequence covering all Gang of Four (GoF) design patterns with clean UML diagrams, Java implementations, and architectural refactorings.',
        url: 'https://www.youtube.com/playlist?list=PLF206E906175C7E07',
        lectureKey: 'cs701-derek-banas-patterns'
    },
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: 'Microservices & Distributed Architecture Principles',
        lecturer: 'Martin Fowler',
        type: 'video',
        typeLabel: 'Thought Leader Keynote',
        topics: ['Componentization via Services', 'Organized around Business Capabilities', 'Smart Endpoints & Dumb Pipes', 'Decentralized Data Management'],
        description: 'Seminal keynote by Martin Fowler explaining microservices characteristics, Conway\'s Law, independent deployability, and bounded context domain modeling.',
        url: 'https://www.youtube.com/watch?v=wgdBVIX9ifA',
        lectureKey: 'cs701-martin-fowler-microservices'
    },
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: 'Event-Driven Architecture: Asynchronous Microservices & CQRS',
        lecturer: 'Mark Richards',
        type: 'video',
        typeLabel: 'Architecture Masterclass',
        topics: ['Broker vs Mediator Topology', 'Eventual Consistency', 'Event Sourcing', 'Message Brokers (Kafka/RabbitMQ)'],
        description: 'Deep dive into event-driven design, handling decouple service boundaries, high-throughput message streaming, and distributed transactions.',
        url: 'https://www.youtube.com/watch?v=STKCRSUsyP0',
        lectureKey: 'cs701-event-driven-arch'
    },
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: 'System Design Interview Architectural Fundamentals',
        lecturer: 'Alex Xu (ByteByteGo)',
        type: 'video',
        typeLabel: 'System Scalability',
        topics: ['Horizontal Scaling', 'Load Balancing', 'Consistent Hashing', 'Database Sharding', 'Caching Layers'],
        description: 'Essential architectural guide to designing internet-scale systems with low latency, high availability, and zero single points of failure.',
        url: 'https://www.youtube.com/watch?v=i7twT3x5yv8',
        lectureKey: 'cs701-system-design-alex'
    },

    // --- CS-702-BD: Big Data Analytics ---
    {
        semester: 7,
        subject: 'cs702-bd',
        subjectCode: 'CS-702',
        subjectLabel: 'Big Data Analytics',
        title: 'Big Data & Hadoop Ecosystem Full Course',
        lecturer: 'Edureka',
        type: 'video',
        typeLabel: 'Complete 10-Hour Masterclass',
        topics: ['5Vs of Big Data', 'HDFS Architecture', 'MapReduce Computation', 'YARN Resource Manager', 'Pig & Hive'],
        description: 'Comprehensive 10-hour crash course covering Hadoop cluster architecture, block distribution, NameNode metadata management, MapReduce data flow, and YARN scheduling.',
        url: 'https://www.youtube.com/watch?v=1vbXmCrkT3Y',
        lectureKey: 'cs702-edureka-hadoop-full'
    },
    {
        semester: 7,
        subject: 'cs702-bd',
        subjectCode: 'CS-702',
        subjectLabel: 'Big Data Analytics',
        title: 'Hadoop Architecture & Distributed File System (HDFS) Explained',
        lecturer: 'Simplilearn',
        type: 'video',
        typeLabel: 'Architecture Primer',
        topics: ['NameNode & DataNodes', 'Block Replication (128MB)', 'Heartbeat & Block Reports', 'Rack Awareness'],
        description: 'Clear architectural breakdown of HDFS master-slave topology, fsimage checkpoints, EditLog transaction recording, and fault tolerance.',
        url: 'https://www.youtube.com/watch?v=aReuLtY0YMI',
        lectureKey: 'cs702-hadoop-hdfs-arch'
    },
    {
        semester: 7,
        subject: 'cs702-bd',
        subjectCode: 'CS-702',
        subjectLabel: 'Big Data Analytics',
        title: 'Big Data & Hadoop Ecosystem Complete Tutorial',
        lecturer: 'Knowledge Hut',
        type: 'video',
        typeLabel: 'Ecosystem Overview',
        topics: ['Apache Spark', 'Resilient Distributed Datasets (RDD)', 'Hadoop MapReduce', 'Data Warehousing'],
        description: 'Practical exploration of big data compute engines, in-memory vs disk-based batch execution, and analytical querying.',
        url: 'https://www.youtube.com/watch?v=gI-qXk7XojA',
        lectureKey: 'cs702-bigdata-ecosystem'
    },

    // --- CS-702-WMC: Wireless & Mobile Computing ---
    {
        semester: 7,
        subject: 'cs702-wmc',
        subjectCode: 'CS-702-WMC',
        subjectLabel: 'Wireless & Mobile Computing',
        title: 'Wireless & Mobile Computing Unit 1 Full Explanation',
        lecturer: 'Exam Ready Engineering',
        type: 'video',
        typeLabel: 'University Syllabus One-Shot',
        topics: ['Cellular Concept', 'Frequency Reuse', 'Channel Assignment', 'Handoff Strategies', 'Interference'],
        description: 'Complete university unit review covering frequency reuse clusters, co-channel interference ratio, cell splitting, sectoring, and handoff mechanisms.',
        url: 'https://www.youtube.com/watch?v=zMhDQR5vDec',
        lectureKey: 'cs702wmc-unit1-oneshot'
    },
    {
        semester: 7,
        subject: 'cs702-wmc',
        subjectCode: 'CS-702-WMC',
        subjectLabel: 'Wireless & Mobile Computing',
        title: 'Wireless & Mobile Computing Important Questions & Systems',
        lecturer: 'Engineering Prep',
        type: 'video',
        typeLabel: 'Core Concepts & Exam Prep',
        topics: ['GSM Architecture', 'HLR & VLR', 'Mobile IP', 'IEEE 802.11 WLAN', 'Bluetooth Topology'],
        description: 'Comprehensive coverage of GSM network elements (BSS, NSS, OSS), Home Location Register, Mobile IP foreign agent discovery, and wireless protocols.',
        url: 'https://www.youtube.com/watch?v=Y02cGHYEgv8',
        lectureKey: 'cs702wmc-systems-prep'
    },
    {
        semester: 7,
        subject: 'cs702-wmc',
        subjectCode: 'CS-702-WMC',
        subjectLabel: 'Wireless & Mobile Computing',
        title: 'Wireless Networking & Radio Signals Crash Course',
        lecturer: 'CrashCourse (Carrie Anne Philbin)',
        type: 'video',
        typeLabel: 'Foundational Theory',
        topics: ['Radio Frequencies', 'Cellular Generations (3G, 4G, 5G)', 'Wi-Fi Multipath', 'Modulation'],
        description: 'Intuitive overview of electromagnetic spectrum propagation, wireless modulation schemes, packet collisions, and wireless security encryption.',
        url: 'https://www.youtube.com/watch?v=3QhU9jd03a0',
        lectureKey: 'cs702wmc-wireless-crashcourse'
    },

    // --- CS-703-CIS: Cryptography & Information Security ---
    {
        semester: 7,
        subject: 'cs703-cis',
        subjectCode: 'CS-703',
        subjectLabel: 'Cryptography & Info Security',
        title: 'Diffie-Hellman Key Exchange & Discrete Logarithm Problem',
        lecturer: 'Computerphile (Dr. Mike Pound)',
        type: 'video',
        typeLabel: 'Cryptographic Masterclass',
        topics: ['Primitive Roots', 'Discrete Logarithm', 'Public Key Negotiation', 'Man-In-The-Middle Attack', 'ECDH'],
        description: 'Internationally acclaimed visual explanation of the Diffie-Hellman protocol, modular exponentiation math, and why computing discrete logarithms is computationally intractable.',
        url: 'https://www.youtube.com/watch?v=NmM9HA2MQGI',
        lectureKey: 'cs703-diffie-hellman-guide'
    },
    {
        semester: 7,
        subject: 'cs703-cis',
        subjectCode: 'CS-703',
        subjectLabel: 'Cryptography & Info Security',
        title: 'Cryptography & Network Security Complete Course',
        lecturer: 'Gate Smashers',
        type: 'playlist',
        typeLabel: 'Full Course Playlist',
        topics: ['Classical Ciphers', 'DES & AES Feistel Networks', 'RSA Numericals', 'Diffie-Hellman', 'Digital Signatures', 'X.509 PKI'],
        description: 'Complete university curriculum covering cryptographic algorithms, substitution/permutation ciphers, round transformations, HMACs, and certificate authority hierarchies.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiHcmS4i14bI0VrMbZTUvlTa',
        lectureKey: 'cs703-gate-smashers-cis'
    },
    {
        semester: 7,
        subject: 'cs703-cis',
        subjectCode: 'CS-703',
        subjectLabel: 'Cryptography & Info Security',
        title: 'How RSA Encryption Works - Computerphile',
        lecturer: 'Computerphile (Dr. Mike Pound)',
        type: 'video',
        typeLabel: 'Algorithm Deep Dive',
        topics: ['Prime Factorization', 'Modulus N', 'Totient Function', 'Public & Private Exponent Math'],
        description: 'Crystal-clear derivation of the RSA asymmetric cryptosystem with small-number examples and explanation of prime factorization security.',
        url: 'https://www.youtube.com/watch?v=JD72Ry60eP4',
        lectureKey: 'cs703-rsa-computerphile'
    },
    {
        semester: 7,
        subject: 'cs703-cis',
        subjectCode: 'CS-703',
        subjectLabel: 'Cryptography & Info Security',
        title: 'Hash Functions, SHA-256 & Avalanche Effect',
        lecturer: 'Computerphile',
        type: 'video',
        typeLabel: 'Core Cryptographic Primitive',
        topics: ['One-Way Property', 'Collision Resistance', 'Merkle-Damgard Construction', 'Avalanche Effect'],
        description: 'Comprehensive breakdown of cryptographic hashing, bit shifting, message schedules, padding bytes, and the mathematical proof of the birthday paradox collision resistance.',
        url: 'https://www.youtube.com/watch?v=DMtFhACPnTY',
        lectureKey: 'cs703-hash-functions-sha'
    },
    {
        semester: 7,
        subject: 'cs703-cis',
        subjectCode: 'CS-703',
        subjectLabel: 'Cryptography & Info Security',
        title: 'Cryptography Full Course - Modern Cryptographic Systems',
        lecturer: 'freeCodeCamp',
        type: 'video',
        typeLabel: 'Comprehensive Course',
        topics: ['Symmetric Encryption', 'Block Ciphers', 'Stream Ciphers', 'Elliptic Curve Cryptography (ECC)'],
        description: 'In-depth university-grade coverage of cryptographic primitives, zero-knowledge proofs, digital signatures, and TLS handshakes.',
        url: 'https://www.youtube.com/watch?v=2aHkqB2-46k',
        lectureKey: 'cs703-fcc-crypto-full'
    },

    // --- CS-703-DM: Disaster Management ---
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'Introduction to Disaster Management & Hazard Classifications',
        lecturer: 'Ristal Institute',
        type: 'video',
        typeLabel: 'Core University Curriculum',
        topics: ['Natural vs Man-Made Hazards', 'Vulnerability Assessment', 'Disaster Impact', 'Risk Communication'],
        description: 'Comprehensive introductory lecture explaining disaster terminology, classification of geological/hydrological/meteorological hazards, and risk evaluation frameworks.',
        url: 'https://www.youtube.com/watch?v=KiIDyzhXRt0',
        lectureKey: 'cs703dm-intro-disasters'
    },
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'Disaster Risk Reduction & Emergency Preparedness Fundamentals',
        lecturer: 'DAV University (Dr. Ranjodh Singh)',
        type: 'video',
        typeLabel: 'Academic Lecture',
        topics: ['Disaster Management Cycle', 'Mitigation Strategies', 'Preparedness & Response', 'Community Awareness'],
        description: 'Detailed lecture examining the cyclical phases of disaster management: prevention, mitigation, preparedness, early warning, relief, and post-disaster rehabilitation.',
        url: 'https://www.youtube.com/watch?v=r8gUXBCQFFc',
        lectureKey: 'cs703dm-risk-reduction'
    },
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'Natural Hazards & Earthquake Engineering Building Safety',
        lecturer: 'Practical Engineering',
        type: 'video',
        typeLabel: 'Structural Mitigation',
        topics: ['Seismic Waves', 'Liquefaction', 'Base Isolation', 'Tuned Mass Dampers', 'Building Codes'],
        description: 'Engineering breakdown of seismic hazard propagation, resonance amplification in structural frameworks, and modern earthquake mitigation technologies.',
        url: 'https://www.youtube.com/watch?v=e7ho6z32yyo',
        lectureKey: 'cs703dm-earthquake-hazards'
    },
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'Tsunami Generation, Coastal Hazards & Early Warning Systems',
        lecturer: 'Practical Engineering',
        type: 'video',
        typeLabel: 'Coastal Risk Management',
        topics: ['Subduction Zones', 'Tsunami Buoys (DART)', 'Inundation Mapping', 'Evacuation Protocols'],
        description: 'Detailed case studies and engineering analysis of megathrust submarine earthquakes, open ocean wave dynamics, runup velocity, and sensor early-warning networks.',
        url: 'https://www.youtube.com/watch?v=Wx9vPv-T51I',
        lectureKey: 'cs703dm-tsunami-warning'
    },

    // --- EXPANDED HIGH-YIELD CURRICULUM LECTURES ---
    // Semester 5: CS-501 (TOC)
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'Turing Machine Construction & Transition Table with Solved Examples',
        lecturer: 'Gate Smashers (Varun Singla)',
        type: 'video',
        typeLabel: 'Solved Numerical',
        topics: ['Turing Machine Model', 'Transition Functions', 'Language Acceptance L={a^n b^n c^n}', 'Infinite Tape'],
        description: 'Complete step-by-step design of standard Turing machines, instantaneous description (ID), multi-track models, and formal tape movements.',
        url: 'https://www.youtube.com/watch?v=5Q_WzH6EfvY',
        lectureKey: 'cs501-turing-machine-design'
    },
    {
        semester: 5,
        subject: 'cs501',
        subjectCode: 'CS-501',
        subjectLabel: 'Theory of Computation',
        title: 'Decidability, Undecidability & The Halting Problem In-Depth',
        lecturer: 'Neso Academy',
        type: 'video',
        typeLabel: 'Core Foundations',
        topics: ['Halting Problem', 'Diagonalization Language', 'Rice Theorem', 'Post Correspondence Problem (PCP)'],
        description: 'Rigorous theoretical exploration of computational limits, proofs of undecidability via Turing reduction, and language classifications.',
        url: 'https://www.youtube.com/watch?v=92WHN-2hkXA',
        lectureKey: 'cs501-decidability-halting'
    },

    // Semester 5: CS-502 (DBMS)
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'B-Tree & B+ Tree Indexing in Relational Databases',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Data Structures & Storage',
        topics: ['B+ Tree Node Split', 'Multi-Level Indexing', 'Order of B Tree', 'Disk Block I/O Optimization'],
        description: 'Comprehensive derivation of tree node fanout, maximum keys, search time complexity, and internal node pointer mechanisms.',
        url: 'https://www.youtube.com/watch?v=aZjYr87r1b8',
        lectureKey: 'cs502-btree-bplus-indexing'
    },
    {
        semester: 5,
        subject: 'cs502',
        subjectCode: 'CS-502',
        subjectLabel: 'Database Management Systems',
        title: 'Two-Phase Locking (2PL), Strict 2PL & Deadlock Avoidance',
        lecturer: 'Knowledge Gate',
        type: 'video',
        typeLabel: 'Concurrency Control',
        topics: ['Growing & Shrinking Phase', 'Cascadelessness', 'Wait-Die vs Wound-Wait', 'Conflict Serializability'],
        description: 'Detailed analysis of concurrency control protocols, strict 2PL vs rigorous 2PL guarantees, and deadlock prevention algorithms.',
        url: 'https://www.youtube.com/watch?v=mD72xP8n0s8',
        lectureKey: 'cs502-2pl-deadlock-handling'
    },

    // Semester 5: CS-503 (Data Analytics)
    {
        semester: 5,
        subject: 'cs503',
        subjectCode: 'CS-503',
        subjectLabel: 'Data Analytics',
        title: 'Logistic Regression & Confusion Matrix Derivation from Scratch',
        lecturer: 'StatQuest with Josh Starmer',
        type: 'video',
        typeLabel: 'Machine Learning Math',
        topics: ['Sigmoid Curve', 'Log-Odds / Logit', 'Maximum Likelihood Estimation', 'Precision & Recall'],
        description: 'Clear visual mathematical breakdown of binary classification, cross-entropy cost function, and ROC/AUC performance evaluation.',
        url: 'https://www.youtube.com/watch?v=yIYKR4sgzI8',
        lectureKey: 'cs503-logistic-regression-statquest'
    },
    {
        semester: 5,
        subject: 'cs503',
        subjectCode: 'CS-503',
        subjectLabel: 'Data Analytics',
        title: 'Principal Component Analysis (PCA) Step-by-Step Dimensionality Reduction',
        lecturer: 'StatQuest with Josh Starmer',
        type: 'video',
        typeLabel: 'Dimensionality Reduction',
        topics: ['Covariance Matrix', 'Eigenvectors & Eigenvalues', 'Variance Explained', 'Scree Plots'],
        description: 'Intuitive geometric explanation of how PCA identifies principal axes of maximal variance and compresses high-dimensional datasets.',
        url: 'https://www.youtube.com/watch?v=FgakZw6K1QQ',
        lectureKey: 'cs503-pca-statquest'
    },

    // Semester 5: CS-503-CS (Cyber Security)
    {
        semester: 5,
        subject: 'cs503-cs',
        subjectCode: 'CS-503-CS',
        subjectLabel: 'Cyber Security',
        title: 'SQL Injection (SQLi) Attacks Explained & Defended',
        lecturer: 'Computerphile (Dr. Mike Pound)',
        type: 'video',
        typeLabel: 'Application Security',
        topics: ['Tautology Injection', 'Parameterized Queries / Prepared Statements', 'Input Sanitization', 'WAF'],
        description: 'Hands-on breakdown of database injection vulnerabilities, union-based queries, and programmatic defense with parameterized SQL.',
        url: 'https://www.youtube.com/watch?v=_jKylhJtPmI',
        lectureKey: 'cs503cs-sqli-computerphile'
    },
    {
        semester: 5,
        subject: 'cs503-cs',
        subjectCode: 'CS-503-CS',
        subjectLabel: 'Cyber Security',
        title: 'Buffer Overflow Vulnerability & Stack Smashing Exploitation',
        lecturer: 'LiveOverflow',
        type: 'video',
        typeLabel: 'Binary Exploitation',
        topics: ['Stack Frames (EIP/ESP)', 'Return Address Overwrite', 'Shellcode Execution', 'ASLR & Stack Canaries'],
        description: 'In-depth low-level memory examination of x86 calling conventions, buffer boundaries, stack corruption, and hardware mitigation.',
        url: 'https://www.youtube.com/watch?v=1S0aBV-Waeo',
        lectureKey: 'cs503cs-buffer-overflow-liveoverflow'
    },

    // Semester 5: CS-504 (Web Technology)
    {
        semester: 5,
        subject: 'cs504',
        subjectCode: 'CS-504',
        subjectLabel: 'Web Technology',
        title: 'React.js Complete Modern Masterclass for Front-End Developers',
        lecturer: 'freeCodeCamp (Bob Ziroll)',
        type: 'video',
        typeLabel: 'Front-End Framework',
        topics: ['Virtual DOM', 'JSX Architecture', 'State & Props', 'Hooks (useState, useEffect)', 'Component Lifecycle'],
        description: 'In-depth guide to modern declarative UI development, state reconciliation algorithms, custom hooks, and event routing.',
        url: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
        lectureKey: 'cs504-reactjs-masterclass'
    },
    {
        semester: 5,
        subject: 'cs504',
        subjectCode: 'CS-504',
        subjectLabel: 'Web Technology',
        title: 'Node.js & Express RESTful API Development with Middleware',
        lecturer: 'freeCodeCamp (John Smilga)',
        type: 'video',
        typeLabel: 'Server-Side Architecture',
        topics: ['Event Loop & Libuv', 'Express Routing', 'Custom Middleware', 'Async Controllers', 'CORS & Security Headers'],
        description: 'Production-ready backend architecture covering non-blocking asynchronous event handling, HTTP status codes, and modular routing.',
        url: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
        lectureKey: 'cs504-nodejs-express-fcc'
    },

    // Semester 6: CS-601 (Machine Learning)
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Support Vector Machines (SVM) & The Kernel Trick Intuition',
        lecturer: 'StatQuest with Josh Starmer',
        type: 'video',
        typeLabel: 'Supervised Learning',
        topics: ['Maximum Margin Hyperplane', 'Support Vectors', 'Radial Basis Function (RBF)', 'Soft-Margin C Parameter'],
        description: 'Geometric walkthrough of margin maximization, Lagrangian multipliers, and mapping non-linear data into higher dimensional space.',
        url: 'https://www.youtube.com/watch?v=efR1C6CvhmE',
        lectureKey: 'cs601-svm-kernel-statquest'
    },
    {
        semester: 6,
        subject: 'cs601',
        subjectCode: 'CS-601',
        subjectLabel: 'Machine Learning',
        title: 'Convolutional Neural Networks (CNNs) & Visual Feature Extraction',
        lecturer: '3Blue1Brown',
        type: 'video',
        typeLabel: 'Deep Learning & Vision',
        topics: ['Convolution Kernels', 'Feature Maps', 'Pooling Layers (Max/Avg)', 'Stride & Padding', 'Fully Connected Layers'],
        description: 'Stunning mathematical and visual journey into spatial convolution filters, edge detection, and weight sharing in vision networks.',
        url: 'https://www.youtube.com/watch?v=KuXjwB4LzSA',
        lectureKey: 'cs601-cnn-3blue1brown'
    },

    // Semester 6: CS-602 (Computer Networks)
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'Dijkstra Algorithm & Link State Routing Protocol (OSPF)',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Network Layer Routing',
        topics: ['Dijkstra Shortest Path', 'Link State Advertisements (LSA)', 'OSPF Cost Metric', 'Convergence Time'],
        description: 'Rigorous calculation of shortest path spanning trees, routing table population, and intra-autonomous system protocol mechanics.',
        url: 'https://www.youtube.com/watch?v=XB4MIexjvY0',
        lectureKey: 'cs602-dijkstra-ospf'
    },
    {
        semester: 6,
        subject: 'cs602',
        subjectCode: 'CS-602',
        subjectLabel: 'Computer Networks',
        title: 'TCP Congestion Control Deep Dive: AIMD, Slow Start & Fast Recovery',
        lecturer: 'Hussein Nasser',
        type: 'video',
        typeLabel: 'Transport Protocols',
        topics: ['Congestion Window (cwnd)', 'Threshold (ssthresh)', 'Duplicate ACKs', 'TCP Reno vs Tahoe'],
        description: 'Detailed analysis of network queuing delay, packet loss detection, additive increase multiplicative decrease, and throughput graphs.',
        url: 'https://www.youtube.com/watch?v=J_jZ3ZqH1qE',
        lectureKey: 'cs602-tcp-congestion-aimd'
    },

    // Semester 6: CS-603 (Compiler Design)
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'Construction of LR(0) and SLR(1) Parsing Tables with Solved Problems',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Bottom-Up Parsing',
        topics: ['Canonical Collection of Items', 'Shift-Reduce Conflicts', 'FOLLOW Set Computation', 'SLR(1) Table'],
        description: 'Complete algorithm for constructing DFA of LR(0) items, resolving shift/reduce ambiguities, and handling lookahead symbols.',
        url: 'https://www.youtube.com/watch?v=8b3q26f1pEw',
        lectureKey: 'cs603-lr0-slr1-parsing'
    },
    {
        semester: 6,
        subject: 'cs603',
        subjectCode: 'CS-603',
        subjectLabel: 'Compiler Design',
        title: 'Intermediate Code Generation: Three Address Code & Quadruple Tables',
        lecturer: 'Knowledge Gate',
        type: 'video',
        typeLabel: 'Code Generation',
        topics: ['Three Address Code (TAC)', 'Quadruples & Triples', 'Syntax Directed Translation', 'Backpatching'],
        description: 'Step-by-step translation of high-level control structures (if-else, while, boolean expressions) into linear 3-address instructions.',
        url: 'https://www.youtube.com/watch?v=1q2d8q7p9pM',
        lectureKey: 'cs603-three-address-code'
    },

    // Semester 6: CS-603-CG (Computer Graphics)
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: '3D Geometric Transformations: Translation, Scaling & Homogeneous Matrices',
        lecturer: 'The Cherno',
        type: 'video',
        typeLabel: '3D Mathematics & Shaders',
        topics: ['Matrix Multiplication (4x4)', 'Homogeneous Coordinates', 'Euler Angles & Quaternions', 'Model-View-Projection (MVP)'],
        description: 'Matrix formulations for linear spatial transformations in 3D coordinate space, camera view space, and clip-space projection.',
        url: 'https://www.youtube.com/watch?v=d_i87_Xw7qI',
        lectureKey: 'cs603cg-3d-transformations'
    },
    {
        semester: 6,
        subject: 'cs603-cg',
        subjectCode: 'CS-603-CG',
        subjectLabel: 'Computer Graphics',
        title: 'Cohen-Sutherland 2D Line Clipping Algorithm Solved Example',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Clipping Algorithms',
        topics: ['Region Codes (TBRL)', 'Bitwise AND / OR Test', 'Intersection Calculation', 'Window-to-Viewport Mapping'],
        description: '4-bit outcode assignment for 9 rectangular regions, trivial accept/reject evaluations, and slope-intercept intersection solving.',
        url: 'https://www.youtube.com/watch?v=4yH_M1Zt-fI',
        lectureKey: 'cs603cg-cohen-sutherland-clipping'
    },

    // Semester 6: CS-604 (Software Project Management)
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'COCOMO Model for Software Cost, Effort & Duration Estimation',
        lecturer: 'Gate Smashers',
        type: 'video',
        typeLabel: 'Quantitative Estimation',
        topics: ['Basic vs Intermediate COCOMO', 'Organic / Semidetached / Embedded Modes', 'Effort Equations (Person-Months)', 'Cost Drivers'],
        description: 'Empirical estimation formulas based on KLOC (Kilo Lines of Code), effort multipliers, cost drivers, and project sizing.',
        url: 'https://www.youtube.com/watch?v=u8k0jZ0H0kM',
        lectureKey: 'cs604-cocomo-estimation'
    },
    {
        semester: 6,
        subject: 'cs604',
        subjectCode: 'CS-604',
        subjectLabel: 'Project Management',
        title: 'Agile Scrum Framework Masterclass: Sprints, Ceremonies & Artifacts',
        lecturer: 'freeCodeCamp',
        type: 'video',
        typeLabel: 'Agile Methodologies',
        topics: ['Sprint Planning', 'Daily Standup', 'Sprint Review & Retrospective', 'Product Backlog Refinement'],
        description: 'Practical exploration of user stories, acceptance criteria, velocity calculation, burndown charts, and Scrum Master facilitation.',
        url: 'https://www.youtube.com/watch?v=2Vt7Ik8Ubl8',
        lectureKey: 'cs604-agile-scrum-fcc'
    },

    // Semester 7: CS-701 (Software Architecture)
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: 'Microservices Architecture Patterns, API Gateways & Service Discovery',
        lecturer: 'Fireship',
        type: 'video',
        typeLabel: 'System Architecture',
        topics: ['Monolith vs Microservices', 'API Gateway Pattern', 'Service Registry (Eureka/Consul)', 'Circuit Breaker (Resilience4j)'],
        description: 'Fast-paced architectural overview of microservice boundaries, asynchronous communication, database-per-service, and resiliency patterns.',
        url: 'https://www.youtube.com/watch?v=rv4LlmLmVWk',
        lectureKey: 'cs701-microservices-patterns'
    },
    {
        semester: 7,
        subject: 'cs701',
        subjectCode: 'CS-701',
        subjectLabel: 'Software Architectures',
        title: 'Event-Driven Architecture & Message Brokers in Distributed Systems',
        lecturer: 'Amigoscode',
        type: 'video',
        typeLabel: 'Distributed Systems',
        topics: ['Event Producers & Consumers', 'Message Queues vs Event Streams', 'Publish-Subscribe Pattern', 'Idempotency'],
        description: 'Architecting decoupled, highly scalable systems using asynchronous event ingestion, consumer groups, and eventual consistency.',
        url: 'https://www.youtube.com/watch?v=R8m3OqK8k4g',
        lectureKey: 'cs701-event-driven-architecture'
    },

    // Semester 7: CS-702-BD (Big Data Analytics)
    {
        semester: 7,
        subject: 'cs702-bd',
        subjectCode: 'CS-702-BD',
        subjectLabel: 'Big Data Analytics',
        title: 'Apache Spark Complete Architecture, Resilient Distributed Datasets (RDDs) & DAGs',
        lecturer: 'Simplilearn',
        type: 'video',
        typeLabel: 'Big Data Processing',
        topics: ['Spark Driver & Executors', 'Transformations vs Actions', 'In-Memory Caching', 'Spark SQL & DataFrames'],
        description: 'Deep dive into distributed in-memory computing, DAG execution plans, catalyst optimizer, and cluster manager coordination.',
        url: 'https://www.youtube.com/watch?v=_C8kWso4dU4',
        lectureKey: 'cs702bd-spark-architecture'
    },
    {
        semester: 7,
        subject: 'cs702-bd',
        subjectCode: 'CS-702-BD',
        subjectLabel: 'Big Data Analytics',
        title: 'Apache Kafka Crash Course: Topics, Partitions, Offsets & Consumer Groups',
        lecturer: 'freeCodeCamp',
        type: 'video',
        typeLabel: 'Distributed Streaming',
        topics: ['Distributed Commit Log', 'Partition Rebalancing', 'Zookeeper vs KRaft', 'Retention Policies'],
        description: 'Hands-on architectural breakdown of enterprise event streaming, write-ahead logs, zero-copy reads, and horizontal scaling.',
        url: 'https://www.youtube.com/watch?v=R873BlNVUB4',
        lectureKey: 'cs702bd-kafka-crash-course'
    },

    // Semester 7: CS-702-WMC (Wireless & Mobile Computing)
    {
        semester: 7,
        subject: 'cs702-wmc',
        subjectCode: 'CS-702-WMC',
        subjectLabel: 'Wireless & Mobile Computing',
        title: '5G New Radio (NR) Architecture, Massive MIMO & Beamforming Technology',
        lecturer: 'Telco Antennas',
        type: 'video',
        typeLabel: 'Next-Gen Wireless',
        topics: ['Sub-6GHz vs mmWave', 'Beamforming Matrices', 'Network Slicing', 'Orthogonal Frequency Division Multiplexing (OFDM)'],
        description: 'Technical evaluation of 5G air interface specifications, beam-steering algorithms, latency reduction, and gNodeB cell architecture.',
        url: 'https://www.youtube.com/watch?v=MC_SfKh5-GE',
        lectureKey: 'cs702wmc-5g-massive-mimo'
    },
    {
        semester: 7,
        subject: 'cs702-wmc',
        subjectCode: 'CS-702-WMC',
        subjectLabel: 'Wireless & Mobile Computing',
        title: 'Mobile IP Architecture: Home Agent, Foreign Agent & Triangular Routing',
        lecturer: 'Knowledge Gate',
        type: 'video',
        typeLabel: 'Mobile Networking',
        topics: ['Home Address vs Care-of Address (CoA)', 'Tunneling & Encapsulation', 'Triangular Routing Problem', 'Route Optimization'],
        description: 'Comprehensive protocol walkthrough of how mobile nodes maintain persistent TCP connections while roaming across alien subnets.',
        url: 'https://www.youtube.com/watch?v=q6g6r8t8kQc',
        lectureKey: 'cs702wmc-mobile-ip-routing'
    },

    // Semester 7: CS-703-CIS (Cryptography & Information Security)
    {
        semester: 7,
        subject: 'cs703-cis',
        subjectCode: 'CS-703-CIS',
        subjectLabel: 'Cryptography & Info Security',
        title: 'Advanced Encryption Standard (AES) Algorithm & Round Transformations',
        lecturer: 'Computerphile (Dr. Mike Pound)',
        type: 'video',
        typeLabel: 'Symmetric Cryptography',
        topics: ['SubBytes (S-Box)', 'ShiftRows Permutation', 'MixColumns Galois Field (GF(2^8))', 'AddRoundKey'],
        description: 'Complete mathematical inspection of the 128-bit block cipher, substitution-permutation network, key expansion, and differential cryptanalysis resistance.',
        url: 'https://www.youtube.com/watch?v=O4xNJsbiN6s',
        lectureKey: 'cs703cis-aes-computerphile'
    },
    {
        semester: 7,
        subject: 'cs703-cis',
        subjectCode: 'CS-703-CIS',
        subjectLabel: 'Cryptography & Info Security',
        title: 'Diffie-Hellman Key Exchange Algorithm Explained with Color Mixing Analogy',
        lecturer: 'Art of the Problem',
        type: 'video',
        typeLabel: 'Asymmetric Cryptography',
        topics: ['Discrete Logarithm Problem', 'Primitive Roots Modulo P', 'Shared Secret Derivation', 'Man-in-the-Middle Countermeasures'],
        description: 'Celebrated intuitive explanation of one-way mathematical functions allowing two parties to establish a shared cryptographic secret over an unencrypted channel.',
        url: 'https://www.youtube.com/watch?v=NmM9HA2MQGI',
        lectureKey: 'cs703cis-diffie-hellman-explained'
    },

    // Semester 7: CS-703-DM (Disaster Management)
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'Remote Sensing & GIS Spatial Analysis in Flood & Landslide Mitigation',
        lecturer: 'NPTEL (IIT Roorkee)',
        type: 'video',
        typeLabel: 'Geospatial Technology',
        topics: ['Satellite Multispectral Imagery', 'DEM Digital Elevation Models', 'Inundation Modeling', 'Hazard Zonation Mapping'],
        description: 'University level lecture on satellite remote sensing data integration, thematic GIS layer overlay, slope stability calculation, and vulnerable zone forecasting.',
        url: 'https://www.youtube.com/watch?v=kYJ0l8D8r1I',
        lectureKey: 'cs703dm-gis-remote-sensing'
    },
    {
        semester: 7,
        subject: 'cs703-dm',
        subjectCode: 'CS-703-DM',
        subjectLabel: 'Disaster Management',
        title: 'Incident Command System (ICS) & Emergency Operations Center Coordination',
        lecturer: 'NIDM India / FEMA',
        type: 'video',
        typeLabel: 'Operational Frameworks',
        topics: ['Incident Commander Responsibilities', 'Operations & Logistics Sections', 'Unified Command Structure', 'Standard Operating Procedures'],
        description: 'Professional disaster response management breakdown of standardized on-scene organizational structures, inter-agency communication, and tactical resource deployment.',
        url: 'https://www.youtube.com/watch?v=3W_T7JvX5vM',
        lectureKey: 'cs703dm-incident-command-system'
    }
];
